// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:471

#ifndef _TAO_IDL_APPEXTENDEDS_H_
#define _TAO_IDL_APPEXTENDEDS_H_


#include "AppExtendedC.h"
#include "CommonTypedefsS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_TypesModule
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module TypesModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:87
  
  class BaseService;
  typedef BaseService *BaseService_ptr;
  
  class  BaseService
    : public virtual PortableServer::ServantBase
  {
  protected:
    BaseService (void);
  
  public:
    // Useful for template programming.
    typedef ::BaseModule::BaseService _stub_type;
    typedef ::BaseModule::BaseService_ptr _stub_ptr_type;
    typedef ::BaseModule::BaseService_var _stub_var_type;
    
    BaseService (const BaseService& rhs);
    virtual ~BaseService (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::BaseModule::BaseService *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void ping (void) = 0;
    
    static void ping_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual char * get_info (void) = 0;
    
    static void get_info_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module BaseModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:87
  
  class Config;
  typedef Config *Config_ptr;
  
  class  Config
    : public virtual POA_BaseModule::BaseService
  {
  protected:
    Config (void);
  
  public:
    // Useful for template programming.
    typedef ::ConfigModule::Config _stub_type;
    typedef ::ConfigModule::Config_ptr _stub_ptr_type;
    typedef ::ConfigModule::Config_var _stub_var_type;
    
    Config (const Config& rhs);
    virtual ~Config (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::ConfigModule::Config *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void get_value (
      const char * key,
      ::CORBA::String_out value) = 0;
    
    static void get_value_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void set_value (
      const char * key,
      const char * value) = 0;
    
    static void set_value_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual ::CORBA::Boolean try_get (
      const char * key,
      char *& value) = 0;
    
    static void try_get_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual ::CORBA::Long get_counter (
      ::CORBA::Long_out current) = 0;
    
    static void get_counter_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void set_entry (
      const ::TypesModule::ConfigEntry & e) = 0;
    
    static void set_entry_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual ::TypesModule::ConfigEntry * get_entry (
      const char * key) = 0;
    
    static void get_entry_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_interface.cpp:2061
    
    static void
    ping_skel (
        TAO_ServerRequest & server_request, 
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_interface.cpp:2061
    
    static void
    get_info_skel (
        TAO_ServerRequest & server_request, 
        void * servant_upcall,
        void * servant
      );
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module ConfigModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:87
  
  class ClientCallback;
  typedef ClientCallback *ClientCallback_ptr;
  
  class  ClientCallback
    : public virtual PortableServer::ServantBase
  {
  protected:
    ClientCallback (void);
  
  public:
    // Useful for template programming.
    typedef ::DataServiceModule::ClientCallback _stub_type;
    typedef ::DataServiceModule::ClientCallback_ptr _stub_ptr_type;
    typedef ::DataServiceModule::ClientCallback_var _stub_var_type;
    
    ClientCallback (const ClientCallback& rhs);
    virtual ~ClientCallback (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::DataServiceModule::ClientCallback *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void on_telemetry (
      const ::TypesModule::SensorData & data) = 0;
    
    static void on_telemetry_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void on_config (
      const ::TypesModule::ConfigSnapshot & cfg) = 0;
    
    static void on_config_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:87
  
  class DataService;
  typedef DataService *DataService_ptr;
  
  class  DataService
    : public virtual POA_BaseModule::BaseService
  {
  protected:
    DataService (void);
  
  public:
    // Useful for template programming.
    typedef ::DataServiceModule::DataService _stub_type;
    typedef ::DataServiceModule::DataService_ptr _stub_ptr_type;
    typedef ::DataServiceModule::DataService_var _stub_var_type;
    
    DataService (const DataService& rhs);
    virtual ~DataService (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::DataServiceModule::DataService *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void register_client (
      const char * client_id) = 0;
    
    static void register_client_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void submit_sensor (
      const ::TypesModule::SensorData & data) = 0;
    
    static void submit_sensor_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual ::TypesModule::SensorData * get_sensor (
      ::CORBA::Long id) = 0;
    
    static void get_sensor_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void register_callback (
      ::DataServiceModule::ClientCallback_ptr cb) = 0;
    
    static void register_callback_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_interface.cpp:2061
    
    static void
    ping_skel (
        TAO_ServerRequest & server_request, 
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // be/be_interface.cpp:2061
    
    static void
    get_info_skel (
        TAO_ServerRequest & server_request, 
        void * servant_upcall,
        void * servant
      );
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module DataServiceModule

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1514


#if defined (__ACE_INLINE__)
#include "AppExtendedS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

