// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:375


#include "AppExtendedC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/Sequence_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/AnyTypeCode/Any_Dual_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Object_Argument_T.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Var_Size_Argument_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "AppExtendedC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_SENSORDATA__ARG_TRAITS_)
#define _TYPESMODULE_SENSORDATA__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::SensorData>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::SensorData,
            TAO::Any_Insert_Policy_Stream <TypesModule::SensorData>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGENTRY__ARG_TRAITS_)
#define _TYPESMODULE_CONFIGENTRY__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::ConfigEntry>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::ConfigEntry,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigEntry>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGSNAPSHOT__ARG_TRAITS_)
#define _TYPESMODULE_CONFIGSNAPSHOT__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::ConfigSnapshot>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::ConfigSnapshot,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigSnapshot>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_DATASERVICEMODULE_CLIENTCALLBACK__ARG_TRAITS_)
#define _DATASERVICEMODULE_CLIENTCALLBACK__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<DataServiceModule::ClientCallback>
    : public
        Object_Arg_Traits_T<
            DataServiceModule::ClientCallback_ptr,
            DataServiceModule::ClientCallback_var,
            DataServiceModule::ClientCallback_out,
            TAO::Objref_Traits<DataServiceModule::ClientCallback>,
            TAO::Any_Insert_Policy_Stream <DataServiceModule::ClientCallback_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_StringSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/StringSeq:1.0",
    "StringSeq",
    &CommonTypes::_tc_StringSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_StringSeq =
    &_tao_tc_TypesModule_StringSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_OctetSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/OctetSeq:1.0",
    "OctetSeq",
    &CommonTypes::_tc_OctetSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_OctetSeq =
    &_tao_tc_TypesModule_OctetSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_LongSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/LongSeq:1.0",
    "LongSeq",
    &CommonTypes::_tc_LongSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_LongSeq =
    &_tao_tc_TypesModule_LongSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_DoubleSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/DoubleSeq:1.0",
    "DoubleSeq",
    &CommonTypes::_tc_DoubleSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_DoubleSeq =
    &_tao_tc_TypesModule_DoubleSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_KvSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/KvSeq:1.0",
    "KvSeq",
    &CommonTypes::_tc_KvSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_KvSeq =
    &_tao_tc_TypesModule_KvSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_MetricSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/MetricSeq:1.0",
    "MetricSeq",
    &CommonTypes::_tc_MetricSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_MetricSeq =
    &_tao_tc_TypesModule_MetricSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_InnerDataSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/InnerDataSeq:1.0",
    "InnerDataSeq",
    &CommonTypes::_tc_InnerDataSeq);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_InnerDataSeq =
    &_tao_tc_TypesModule_InnerDataSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_Sample[] =
      {
        { "t_ms", &CORBA::_tc_long },
        { "reading", &CORBA::_tc_double },
        { "payload", &CommonTypes::_tc_OctetSeq }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_Sample (
  ::CORBA::tk_struct,
  "IDL:TypesModule/Sample:1.0",
  "Sample",
  _tao_fields_TypesModule_Sample,
  3);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_Sample =
    &_tao_tc_TypesModule_Sample;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::Sample::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  Sample *_tao_tmp_pointer =
    static_cast<Sample *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from 
// be/be_visitor_sequence/sequence_cs.cpp:65

#if !defined (_TYPESMODULE_SAMPLESEQ_CS_)
#define _TYPESMODULE_SAMPLESEQ_CS_

TypesModule::SampleSeq::SampleSeq (void)
{}

TypesModule::SampleSeq::SampleSeq (
    ::CORBA::ULong max
  )
  : TAO::unbounded_value_sequence<
        Sample
      >
    (max)
{}

TypesModule::SampleSeq::SampleSeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    TypesModule::Sample * buffer,
    ::CORBA::Boolean release
  )
  : TAO::unbounded_value_sequence<
        Sample
      >
    (max, length, buffer, release)
{}

TypesModule::SampleSeq::SampleSeq (
    const SampleSeq &seq
  )
  : TAO::unbounded_value_sequence<
        Sample
      >
    (seq)
{}

TypesModule::SampleSeq::~SampleSeq (void)
{}

void TypesModule::SampleSeq::_tao_any_destructor (
    void * _tao_void_pointer
  )
{
  SampleSeq * _tao_tmp_pointer =
    static_cast<SampleSeq *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516


#ifndef _TAO_TYPECODE_TypesModule_SampleSeq_GUARD
#define _TAO_TYPECODE_TypesModule_SampleSeq_GUARD

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace TAO
{
  namespace TypeCode
  {
    namespace
    {
      TAO::TypeCode::Sequence< ::CORBA::TypeCode_ptr const *,
                              TAO::Null_RefCount_Policy>
        TypesModule_SampleSeq_0 (
          ::CORBA::tk_sequence,
          &TypesModule::_tc_Sample,
          0U);
        
      ::CORBA::TypeCode_ptr const tc_TypesModule_SampleSeq_0 =
        &TypesModule_SampleSeq_0;
    }
  }
}

TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_TYPECODE_TypesModule_SampleSeq_GUARD */

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_SampleSeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/SampleSeq:1.0",
    "SampleSeq",
    &TAO::TypeCode::tc_TypesModule_SampleSeq_0);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_SampleSeq =
    &_tao_tc_TypesModule_SampleSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_Meta[] =
      {
        { "source_id", &CORBA::_tc_long },
        { "source_name", &CORBA::_tc_string },
        { "tags", &CommonTypes::_tc_StringSeq },
        { "attributes", &CommonTypes::_tc_KvSeq },
        { "loc", &CommonTypes::_tc_Location }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_Meta (
  ::CORBA::tk_struct,
  "IDL:TypesModule/Meta:1.0",
  "Meta",
  _tao_fields_TypesModule_Meta,
  5);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_Meta =
    &_tao_tc_TypesModule_Meta;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::Meta::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  Meta *_tao_tmp_pointer =
    static_cast<Meta *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_SensorData[] =
      {
        { "id", &CORBA::_tc_long },
        { "name", &CORBA::_tc_string },
        { "value", &CORBA::_tc_double },
        { "meta", &TypesModule::_tc_Meta },
        { "metrics", &CommonTypes::_tc_MetricSeq },
        { "samples", &TypesModule::_tc_SampleSeq },
        { "histogram", &CommonTypes::_tc_LongSeq },
        { "spectrum", &CommonTypes::_tc_DoubleSeq }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_SensorData (
  ::CORBA::tk_struct,
  "IDL:TypesModule/SensorData:1.0",
  "SensorData",
  _tao_fields_TypesModule_SensorData,
  8);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_SensorData =
    &_tao_tc_TypesModule_SensorData;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::SensorData::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  SensorData *_tao_tmp_pointer =
    static_cast<SensorData *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_ConfigEntry[] =
      {
        { "key", &CORBA::_tc_string },
        { "value", &CORBA::_tc_string },
        { "timestamp", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_ConfigEntry (
  ::CORBA::tk_struct,
  "IDL:TypesModule/ConfigEntry:1.0",
  "ConfigEntry",
  _tao_fields_TypesModule_ConfigEntry,
  3);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_ConfigEntry =
    &_tao_tc_TypesModule_ConfigEntry;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::ConfigEntry::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  ConfigEntry *_tao_tmp_pointer =
    static_cast<ConfigEntry *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from 
// be/be_visitor_sequence/sequence_cs.cpp:65

#if !defined (_TYPESMODULE_CONFIGENTRYSEQ_CS_)
#define _TYPESMODULE_CONFIGENTRYSEQ_CS_

TypesModule::ConfigEntrySeq::ConfigEntrySeq (void)
{}

TypesModule::ConfigEntrySeq::ConfigEntrySeq (
    ::CORBA::ULong max
  )
  : TAO::unbounded_value_sequence<
        ConfigEntry
      >
    (max)
{}

TypesModule::ConfigEntrySeq::ConfigEntrySeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    TypesModule::ConfigEntry * buffer,
    ::CORBA::Boolean release
  )
  : TAO::unbounded_value_sequence<
        ConfigEntry
      >
    (max, length, buffer, release)
{}

TypesModule::ConfigEntrySeq::ConfigEntrySeq (
    const ConfigEntrySeq &seq
  )
  : TAO::unbounded_value_sequence<
        ConfigEntry
      >
    (seq)
{}

TypesModule::ConfigEntrySeq::~ConfigEntrySeq (void)
{}

void TypesModule::ConfigEntrySeq::_tao_any_destructor (
    void * _tao_void_pointer
  )
{
  ConfigEntrySeq * _tao_tmp_pointer =
    static_cast<ConfigEntrySeq *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516


#ifndef _TAO_TYPECODE_TypesModule_ConfigEntrySeq_GUARD
#define _TAO_TYPECODE_TypesModule_ConfigEntrySeq_GUARD

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace TAO
{
  namespace TypeCode
  {
    namespace
    {
      TAO::TypeCode::Sequence< ::CORBA::TypeCode_ptr const *,
                              TAO::Null_RefCount_Policy>
        TypesModule_ConfigEntrySeq_0 (
          ::CORBA::tk_sequence,
          &TypesModule::_tc_ConfigEntry,
          0U);
        
      ::CORBA::TypeCode_ptr const tc_TypesModule_ConfigEntrySeq_0 =
        &TypesModule_ConfigEntrySeq_0;
    }
  }
}

TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_TYPECODE_TypesModule_ConfigEntrySeq_GUARD */

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_TypesModule_ConfigEntrySeq (
    ::CORBA::tk_alias,
    "IDL:TypesModule/ConfigEntrySeq:1.0",
    "ConfigEntrySeq",
    &TAO::TypeCode::tc_TypesModule_ConfigEntrySeq_0);
  
namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_ConfigEntrySeq =
    &_tao_tc_TypesModule_ConfigEntrySeq;
}



// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_OuterData[] =
      {
        { "inner", &CommonTypes::_tc_InnerData },
        { "count", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_OuterData (
  ::CORBA::tk_struct,
  "IDL:TypesModule/OuterData:1.0",
  "OuterData",
  _tao_fields_TypesModule_OuterData,
  2);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_OuterData =
    &_tao_tc_TypesModule_OuterData;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::OuterData::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  OuterData *_tao_tmp_pointer =
    static_cast<OuterData *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:84



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_TypesModule_ConfigSnapshot[] =
      {
        { "entries", &TypesModule::_tc_ConfigEntrySeq },
        { "version", &CORBA::_tc_long },
        { "meta", &TypesModule::_tc_OuterData }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_TypesModule_ConfigSnapshot (
  ::CORBA::tk_struct,
  "IDL:TypesModule/ConfigSnapshot:1.0",
  "ConfigSnapshot",
  _tao_fields_TypesModule_ConfigSnapshot,
  3);

namespace TypesModule
{
  ::CORBA::TypeCode_ptr const _tc_ConfigSnapshot =
    &_tao_tc_TypesModule_ConfigSnapshot;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/structure_cs.cpp:65

void 
TypesModule::ConfigSnapshot::_tao_any_destructor (
    void *_tao_void_pointer
  )
{
  ConfigSnapshot *_tao_tmp_pointer =
    static_cast<ConfigSnapshot *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for BaseModule::BaseService.

BaseModule::BaseService_ptr
TAO::Objref_Traits<BaseModule::BaseService>::duplicate (
    BaseModule::BaseService_ptr p)
{
  return BaseModule::BaseService::_duplicate (p);
}

void
TAO::Objref_Traits<BaseModule::BaseService>::release (
    BaseModule::BaseService_ptr p)
{
  ::CORBA::release (p);
}

BaseModule::BaseService_ptr
TAO::Objref_Traits<BaseModule::BaseService>::nil (void)
{
  return BaseModule::BaseService::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<BaseModule::BaseService>::marshal (
    const BaseModule::BaseService_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
BaseModule::BaseService::ping (void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_BaseService_Proxy_Broker_ == 0)
    {
      BaseModule_BaseService_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "ping",
      4,
      this->the_TAO_BaseService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char *
BaseModule::BaseService::get_info (void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_BaseService_Proxy_Broker_ == 0)
    {
      BaseModule_BaseService_setup_collocation ();
    }
  
  TAO::Arg_Traits< char *>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "get_info",
      8,
      this->the_TAO_BaseService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

BaseModule::BaseService::BaseService (void)
 : the_TAO_BaseService_Proxy_Broker_ (0)
{
  this->BaseModule_BaseService_setup_collocation ();
}

void
BaseModule::BaseService::BaseModule_BaseService_setup_collocation ()
{
  if (::BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_BaseService_Proxy_Broker_ =
        ::BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer (this);
    }
}

BaseModule::BaseService::~BaseService (void)
{}

void 
BaseModule::BaseService::_tao_any_destructor (void *_tao_void_pointer)
{
  BaseService *_tao_tmp_pointer =
    static_cast<BaseService *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

BaseModule::BaseService_ptr
BaseModule::BaseService::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<BaseService>::narrow (
        _tao_objref,
        "IDL:BaseModule/BaseService:1.0",
        BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer
      );
}

BaseModule::BaseService_ptr
BaseModule::BaseService::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<BaseService>::unchecked_narrow (
        _tao_objref,
        "IDL:BaseModule/BaseService:1.0",
        BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer
      );
}

BaseModule::BaseService_ptr
BaseModule::BaseService::_duplicate (BaseService_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
BaseModule::BaseService::_tao_release (BaseService_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
BaseModule::BaseService::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* BaseModule::BaseService::_interface_repository_id (void) const
{
  return "IDL:BaseModule/BaseService:1.0";
}

::CORBA::Boolean
BaseModule::BaseService::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_BaseModule_BaseService (
    ::CORBA::tk_objref,
    "IDL:BaseModule/BaseService:1.0",
    "BaseService");
  
namespace BaseModule
{
  ::CORBA::TypeCode_ptr const _tc_BaseService =
    &_tao_tc_BaseModule_BaseService;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for ConfigModule::Config.

ConfigModule::Config_ptr
TAO::Objref_Traits<ConfigModule::Config>::duplicate (
    ConfigModule::Config_ptr p)
{
  return ConfigModule::Config::_duplicate (p);
}

void
TAO::Objref_Traits<ConfigModule::Config>::release (
    ConfigModule::Config_ptr p)
{
  ::CORBA::release (p);
}

ConfigModule::Config_ptr
TAO::Objref_Traits<ConfigModule::Config>::nil (void)
{
  return ConfigModule::Config::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ConfigModule::Config>::marshal (
    const ConfigModule::Config_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ConfigModule::Config::get_value (
  const char * key,
  ::CORBA::String_out value)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_key (key);
  TAO::Arg_Traits< char *>::out_arg_val _tao_value (value);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_key,
      &_tao_value
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "get_value",
      9,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ConfigModule::Config::set_value (
  const char * key,
  const char * value)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_key (key);
  TAO::Arg_Traits< char *>::in_arg_val _tao_value (value);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_key,
      &_tao_value
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "set_value",
      9,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Boolean
ConfigModule::Config::try_get (
  const char * key,
  char *& value)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_key (key);
  TAO::Arg_Traits< char *>::inout_arg_val _tao_value (value);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_key,
      &_tao_value
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "try_get",
      7,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Long
ConfigModule::Config::get_counter (
  ::CORBA::Long_out current)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::out_arg_val _tao_current (current);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_current
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "get_counter",
      11,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ConfigModule::Config::set_entry (
  const ::TypesModule::ConfigEntry & e)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TypesModule::ConfigEntry>::in_arg_val _tao_e (e);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_e
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "set_entry",
      9,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::TypesModule::ConfigEntry *
ConfigModule::Config::get_entry (
  const char * key)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Config_Proxy_Broker_ == 0)
    {
      ConfigModule_Config_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::TypesModule::ConfigEntry>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_key (key);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_key
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "get_entry",
      9,
      this->the_TAO_Config_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

ConfigModule::Config::Config (void)
 : the_TAO_Config_Proxy_Broker_ (0)
{
  this->ConfigModule_Config_setup_collocation ();
}

void
ConfigModule::Config::ConfigModule_Config_setup_collocation ()
{
  if (::ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Config_Proxy_Broker_ =
        ::ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->BaseModule_BaseService_setup_collocation ();
}

ConfigModule::Config::~Config (void)
{}

void 
ConfigModule::Config::_tao_any_destructor (void *_tao_void_pointer)
{
  Config *_tao_tmp_pointer =
    static_cast<Config *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

ConfigModule::Config_ptr
ConfigModule::Config::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Config>::narrow (
        _tao_objref,
        "IDL:ConfigModule/Config:1.0",
        ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer
      );
}

ConfigModule::Config_ptr
ConfigModule::Config::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Config>::unchecked_narrow (
        _tao_objref,
        "IDL:ConfigModule/Config:1.0",
        ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer
      );
}

ConfigModule::Config_ptr
ConfigModule::Config::_duplicate (Config_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
ConfigModule::Config::_tao_release (Config_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ConfigModule::Config::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:ConfigModule/Config:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* ConfigModule::Config::_interface_repository_id (void) const
{
  return "IDL:ConfigModule/Config:1.0";
}

::CORBA::Boolean
ConfigModule::Config::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_ConfigModule_Config (
    ::CORBA::tk_objref,
    "IDL:ConfigModule/Config:1.0",
    "Config");
  
namespace ConfigModule
{
  ::CORBA::TypeCode_ptr const _tc_Config =
    &_tao_tc_ConfigModule_Config;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for DataServiceModule::ClientCallback.

DataServiceModule::ClientCallback_ptr
TAO::Objref_Traits<DataServiceModule::ClientCallback>::duplicate (
    DataServiceModule::ClientCallback_ptr p)
{
  return DataServiceModule::ClientCallback::_duplicate (p);
}

void
TAO::Objref_Traits<DataServiceModule::ClientCallback>::release (
    DataServiceModule::ClientCallback_ptr p)
{
  ::CORBA::release (p);
}

DataServiceModule::ClientCallback_ptr
TAO::Objref_Traits<DataServiceModule::ClientCallback>::nil (void)
{
  return DataServiceModule::ClientCallback::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DataServiceModule::ClientCallback>::marshal (
    const DataServiceModule::ClientCallback_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
DataServiceModule::ClientCallback::on_telemetry (
  const ::TypesModule::SensorData & data)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ClientCallback_Proxy_Broker_ == 0)
    {
      DataServiceModule_ClientCallback_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TypesModule::SensorData>::in_arg_val _tao_data (data);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_data
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "on_telemetry",
      12,
      this->the_TAO_ClientCallback_Proxy_Broker_,
      TAO::TAO_ONEWAY_INVOCATION
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
DataServiceModule::ClientCallback::on_config (
  const ::TypesModule::ConfigSnapshot & cfg)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ClientCallback_Proxy_Broker_ == 0)
    {
      DataServiceModule_ClientCallback_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TypesModule::ConfigSnapshot>::in_arg_val _tao_cfg (cfg);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_cfg
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "on_config",
      9,
      this->the_TAO_ClientCallback_Proxy_Broker_,
      TAO::TAO_ONEWAY_INVOCATION
    );
  
  _tao_call.invoke (0, 0);
}

DataServiceModule::ClientCallback::ClientCallback (void)
 : the_TAO_ClientCallback_Proxy_Broker_ (0)
{
  this->DataServiceModule_ClientCallback_setup_collocation ();
}

void
DataServiceModule::ClientCallback::DataServiceModule_ClientCallback_setup_collocation ()
{
  if (::DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_ClientCallback_Proxy_Broker_ =
        ::DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer (this);
    }
}

DataServiceModule::ClientCallback::~ClientCallback (void)
{}

void 
DataServiceModule::ClientCallback::_tao_any_destructor (void *_tao_void_pointer)
{
  ClientCallback *_tao_tmp_pointer =
    static_cast<ClientCallback *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

DataServiceModule::ClientCallback_ptr
DataServiceModule::ClientCallback::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<ClientCallback>::narrow (
        _tao_objref,
        "IDL:DataServiceModule/ClientCallback:1.0",
        DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer
      );
}

DataServiceModule::ClientCallback_ptr
DataServiceModule::ClientCallback::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<ClientCallback>::unchecked_narrow (
        _tao_objref,
        "IDL:DataServiceModule/ClientCallback:1.0",
        DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer
      );
}

DataServiceModule::ClientCallback_ptr
DataServiceModule::ClientCallback::_duplicate (ClientCallback_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
DataServiceModule::ClientCallback::_tao_release (ClientCallback_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DataServiceModule::ClientCallback::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:DataServiceModule/ClientCallback:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* DataServiceModule::ClientCallback::_interface_repository_id (void) const
{
  return "IDL:DataServiceModule/ClientCallback:1.0";
}

::CORBA::Boolean
DataServiceModule::ClientCallback::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_DataServiceModule_ClientCallback (
    ::CORBA::tk_objref,
    "IDL:DataServiceModule/ClientCallback:1.0",
    "ClientCallback");
  
namespace DataServiceModule
{
  ::CORBA::TypeCode_ptr const _tc_ClientCallback =
    &_tao_tc_DataServiceModule_ClientCallback;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for DataServiceModule::DataService.

DataServiceModule::DataService_ptr
TAO::Objref_Traits<DataServiceModule::DataService>::duplicate (
    DataServiceModule::DataService_ptr p)
{
  return DataServiceModule::DataService::_duplicate (p);
}

void
TAO::Objref_Traits<DataServiceModule::DataService>::release (
    DataServiceModule::DataService_ptr p)
{
  ::CORBA::release (p);
}

DataServiceModule::DataService_ptr
TAO::Objref_Traits<DataServiceModule::DataService>::nil (void)
{
  return DataServiceModule::DataService::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DataServiceModule::DataService>::marshal (
    const DataServiceModule::DataService_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
DataServiceModule::DataService::register_client (
  const char * client_id)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DataService_Proxy_Broker_ == 0)
    {
      DataServiceModule_DataService_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_client_id (client_id);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_client_id
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "register_client",
      15,
      this->the_TAO_DataService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
DataServiceModule::DataService::submit_sensor (
  const ::TypesModule::SensorData & data)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DataService_Proxy_Broker_ == 0)
    {
      DataServiceModule_DataService_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TypesModule::SensorData>::in_arg_val _tao_data (data);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_data
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "submit_sensor",
      13,
      this->the_TAO_DataService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::TypesModule::SensorData *
DataServiceModule::DataService::get_sensor (
  ::CORBA::Long id)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DataService_Proxy_Broker_ == 0)
    {
      DataServiceModule_DataService_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::TypesModule::SensorData>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_id (id);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_id
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "get_sensor",
      10,
      this->the_TAO_DataService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
DataServiceModule::DataService::register_callback (
  ::DataServiceModule::ClientCallback_ptr cb)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DataService_Proxy_Broker_ == 0)
    {
      DataServiceModule_DataService_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::DataServiceModule::ClientCallback>::in_arg_val _tao_cb (cb);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_cb
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "register_callback",
      17,
      this->the_TAO_DataService_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

DataServiceModule::DataService::DataService (void)
 : the_TAO_DataService_Proxy_Broker_ (0)
{
  this->DataServiceModule_DataService_setup_collocation ();
}

void
DataServiceModule::DataService::DataServiceModule_DataService_setup_collocation ()
{
  if (::DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_DataService_Proxy_Broker_ =
        ::DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->BaseModule_BaseService_setup_collocation ();
}

DataServiceModule::DataService::~DataService (void)
{}

void 
DataServiceModule::DataService::_tao_any_destructor (void *_tao_void_pointer)
{
  DataService *_tao_tmp_pointer =
    static_cast<DataService *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

DataServiceModule::DataService_ptr
DataServiceModule::DataService::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DataService>::narrow (
        _tao_objref,
        "IDL:DataServiceModule/DataService:1.0",
        DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer
      );
}

DataServiceModule::DataService_ptr
DataServiceModule::DataService::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DataService>::unchecked_narrow (
        _tao_objref,
        "IDL:DataServiceModule/DataService:1.0",
        DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer
      );
}

DataServiceModule::DataService_ptr
DataServiceModule::DataService::_duplicate (DataService_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
DataServiceModule::DataService::_tao_release (DataService_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DataServiceModule::DataService::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DataServiceModule/DataService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* DataServiceModule::DataService::_interface_repository_id (void) const
{
  return "IDL:DataServiceModule/DataService:1.0";
}

::CORBA::Boolean
DataServiceModule::DataService::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_DataServiceModule_DataService (
    ::CORBA::tk_objref,
    "IDL:DataServiceModule/DataService:1.0",
    "DataService");
  
namespace DataServiceModule
{
  ::CORBA::TypeCode_ptr const _tc_DataService =
    &_tao_tc_DataServiceModule_DataService;
}



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::Sample &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::Sample *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::Sample>::insert_copy (
        _tao_any,
        TypesModule::Sample::_tao_any_destructor,
        TypesModule::_tc_Sample,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::Sample *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::Sample>::insert (
      _tao_any,
      TypesModule::Sample::_tao_any_destructor,
      TypesModule::_tc_Sample,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::Sample *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::Sample *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::Sample *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::Sample>::extract (
        _tao_any,
        TypesModule::Sample::_tao_any_destructor,
        TypesModule::_tc_Sample,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_sequence/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::SampleSeq &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::SampleSeq *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::SampleSeq>::insert_copy (
        _tao_any,
        TypesModule::SampleSeq::_tao_any_destructor,
        TypesModule::_tc_SampleSeq,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::SampleSeq *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::SampleSeq>::insert (
      _tao_any,
      TypesModule::SampleSeq::_tao_any_destructor,
      TypesModule::_tc_SampleSeq,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::SampleSeq *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::SampleSeq *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::SampleSeq *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::SampleSeq>::extract (
        _tao_any,
        TypesModule::SampleSeq::_tao_any_destructor,
        TypesModule::_tc_SampleSeq,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::Meta &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::Meta *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::Meta>::insert_copy (
        _tao_any,
        TypesModule::Meta::_tao_any_destructor,
        TypesModule::_tc_Meta,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::Meta *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::Meta>::insert (
      _tao_any,
      TypesModule::Meta::_tao_any_destructor,
      TypesModule::_tc_Meta,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::Meta *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::Meta *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::Meta *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::Meta>::extract (
        _tao_any,
        TypesModule::Meta::_tao_any_destructor,
        TypesModule::_tc_Meta,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::SensorData &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::SensorData *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::SensorData>::insert_copy (
        _tao_any,
        TypesModule::SensorData::_tao_any_destructor,
        TypesModule::_tc_SensorData,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::SensorData *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::SensorData>::insert (
      _tao_any,
      TypesModule::SensorData::_tao_any_destructor,
      TypesModule::_tc_SensorData,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::SensorData *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::SensorData *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::SensorData *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::SensorData>::extract (
        _tao_any,
        TypesModule::SensorData::_tao_any_destructor,
        TypesModule::_tc_SensorData,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::ConfigEntry &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::ConfigEntry *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::ConfigEntry>::insert_copy (
        _tao_any,
        TypesModule::ConfigEntry::_tao_any_destructor,
        TypesModule::_tc_ConfigEntry,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::ConfigEntry *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::ConfigEntry>::insert (
      _tao_any,
      TypesModule::ConfigEntry::_tao_any_destructor,
      TypesModule::_tc_ConfigEntry,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::ConfigEntry *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::ConfigEntry *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::ConfigEntry *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::ConfigEntry>::extract (
        _tao_any,
        TypesModule::ConfigEntry::_tao_any_destructor,
        TypesModule::_tc_ConfigEntry,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_sequence/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::ConfigEntrySeq &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::ConfigEntrySeq *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::ConfigEntrySeq>::insert_copy (
        _tao_any,
        TypesModule::ConfigEntrySeq::_tao_any_destructor,
        TypesModule::_tc_ConfigEntrySeq,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::ConfigEntrySeq *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::ConfigEntrySeq>::insert (
      _tao_any,
      TypesModule::ConfigEntrySeq::_tao_any_destructor,
      TypesModule::_tc_ConfigEntrySeq,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::ConfigEntrySeq *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::ConfigEntrySeq *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::ConfigEntrySeq *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::ConfigEntrySeq>::extract (
        _tao_any,
        TypesModule::ConfigEntrySeq::_tao_any_destructor,
        TypesModule::_tc_ConfigEntrySeq,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::OuterData &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::OuterData *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::OuterData>::insert_copy (
        _tao_any,
        TypesModule::OuterData::_tao_any_destructor,
        TypesModule::_tc_OuterData,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::OuterData *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::OuterData>::insert (
      _tao_any,
      TypesModule::OuterData::_tao_any_destructor,
      TypesModule::_tc_OuterData,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::OuterData *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::OuterData *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::OuterData *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::OuterData>::extract (
        _tao_any,
        TypesModule::OuterData::_tao_any_destructor,
        TypesModule::_tc_OuterData,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_structure/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const TypesModule::ConfigSnapshot &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<TypesModule::ConfigSnapshot *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<TypesModule::ConfigSnapshot>::insert_copy (
        _tao_any,
        TypesModule::ConfigSnapshot::_tao_any_destructor,
        TypesModule::_tc_ConfigSnapshot,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    TypesModule::ConfigSnapshot *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<TypesModule::ConfigSnapshot>::insert (
      _tao_any,
      TypesModule::ConfigSnapshot::_tao_any_destructor,
      TypesModule::_tc_ConfigSnapshot,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    TypesModule::ConfigSnapshot *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const TypesModule::ConfigSnapshot *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const TypesModule::ConfigSnapshot *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<TypesModule::ConfigSnapshot>::extract (
        _tao_any,
        TypesModule::ConfigSnapshot::_tao_any_destructor,
        TypesModule::_tc_ConfigSnapshot,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<BaseModule::BaseService>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace BaseModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      BaseService_ptr _tao_elem)
  {
    BaseService_ptr _tao_objptr =
      BaseService::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      BaseService_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<BaseService>::insert (
        _tao_any,
        BaseService::_tao_any_destructor,
        _tc_BaseService,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      BaseService_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<BaseService>::extract (
          _tao_any,
          BaseService::_tao_any_destructor,
          _tc_BaseService,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    BaseModule::BaseService_ptr _tao_elem)
{
  BaseModule::BaseService_ptr _tao_objptr =
    BaseModule::BaseService::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    BaseModule::BaseService_ptr *_tao_elem)
{
  TAO::Any_Impl_T<BaseModule::BaseService>::insert (
      _tao_any,
      BaseModule::BaseService::_tao_any_destructor,
      BaseModule::_tc_BaseService,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    BaseModule::BaseService_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<BaseModule::BaseService>::extract (
        _tao_any,
        BaseModule::BaseService::_tao_any_destructor,
        BaseModule::_tc_BaseService,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<ConfigModule::Config>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ConfigModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Config_ptr _tao_elem)
  {
    Config_ptr _tao_objptr =
      Config::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Config_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Config>::insert (
        _tao_any,
        Config::_tao_any_destructor,
        _tc_Config,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Config_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Config>::extract (
          _tao_any,
          Config::_tao_any_destructor,
          _tc_Config,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ConfigModule::Config_ptr _tao_elem)
{
  ConfigModule::Config_ptr _tao_objptr =
    ConfigModule::Config::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ConfigModule::Config_ptr *_tao_elem)
{
  TAO::Any_Impl_T<ConfigModule::Config>::insert (
      _tao_any,
      ConfigModule::Config::_tao_any_destructor,
      ConfigModule::_tc_Config,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    ConfigModule::Config_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<ConfigModule::Config>::extract (
        _tao_any,
        ConfigModule::Config::_tao_any_destructor,
        ConfigModule::_tc_Config,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<DataServiceModule::ClientCallback>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DataServiceModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ClientCallback_ptr _tao_elem)
  {
    ClientCallback_ptr _tao_objptr =
      ClientCallback::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ClientCallback_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<ClientCallback>::insert (
        _tao_any,
        ClientCallback::_tao_any_destructor,
        _tc_ClientCallback,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      ClientCallback_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<ClientCallback>::extract (
          _tao_any,
          ClientCallback::_tao_any_destructor,
          _tc_ClientCallback,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    DataServiceModule::ClientCallback_ptr _tao_elem)
{
  DataServiceModule::ClientCallback_ptr _tao_objptr =
    DataServiceModule::ClientCallback::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    DataServiceModule::ClientCallback_ptr *_tao_elem)
{
  TAO::Any_Impl_T<DataServiceModule::ClientCallback>::insert (
      _tao_any,
      DataServiceModule::ClientCallback::_tao_any_destructor,
      DataServiceModule::_tc_ClientCallback,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    DataServiceModule::ClientCallback_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<DataServiceModule::ClientCallback>::extract (
        _tao_any,
        DataServiceModule::ClientCallback::_tao_any_destructor,
        DataServiceModule::_tc_ClientCallback,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<DataServiceModule::DataService>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DataServiceModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DataService_ptr _tao_elem)
  {
    DataService_ptr _tao_objptr =
      DataService::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DataService_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<DataService>::insert (
        _tao_any,
        DataService::_tao_any_destructor,
        _tc_DataService,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      DataService_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<DataService>::extract (
          _tao_any,
          DataService::_tao_any_destructor,
          _tc_DataService,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    DataServiceModule::DataService_ptr _tao_elem)
{
  DataServiceModule::DataService_ptr _tao_objptr =
    DataServiceModule::DataService::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    DataServiceModule::DataService_ptr *_tao_elem)
{
  TAO::Any_Impl_T<DataServiceModule::DataService>::insert (
      _tao_any,
      DataServiceModule::DataService::_tao_any_destructor,
      DataServiceModule::_tc_DataService,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    DataServiceModule::DataService_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<DataServiceModule::DataService>::extract (
        _tao_any,
        DataServiceModule::DataService::_tao_any_destructor,
        DataServiceModule::_tc_DataService,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::Sample &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.t_ms) &&
    (strm << _tao_aggregate.reading) &&
    (strm << _tao_aggregate.payload);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::Sample &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.t_ms) &&
    (strm >> _tao_aggregate.reading) &&
    (strm >> _tao_aggregate.payload);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_TypesModule_SampleSeq_CPP_
#define _TAO_CDR_OP_TypesModule_SampleSeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::SampleSeq &_tao_sequence
  )
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::SampleSeq &_tao_sequence
  )
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_TypesModule_SampleSeq_CPP_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::Meta &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.source_id) &&
    (strm << _tao_aggregate.source_name.in ()) &&
    (strm << _tao_aggregate.tags) &&
    (strm << _tao_aggregate.attributes) &&
    (strm << _tao_aggregate.loc);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::Meta &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.source_id) &&
    (strm >> _tao_aggregate.source_name.out ()) &&
    (strm >> _tao_aggregate.tags) &&
    (strm >> _tao_aggregate.attributes) &&
    (strm >> _tao_aggregate.loc);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::SensorData &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.id) &&
    (strm << _tao_aggregate.name.in ()) &&
    (strm << _tao_aggregate.value) &&
    (strm << _tao_aggregate.meta) &&
    (strm << _tao_aggregate.metrics) &&
    (strm << _tao_aggregate.samples) &&
    (strm << _tao_aggregate.histogram) &&
    (strm << _tao_aggregate.spectrum);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::SensorData &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.id) &&
    (strm >> _tao_aggregate.name.out ()) &&
    (strm >> _tao_aggregate.value) &&
    (strm >> _tao_aggregate.meta) &&
    (strm >> _tao_aggregate.metrics) &&
    (strm >> _tao_aggregate.samples) &&
    (strm >> _tao_aggregate.histogram) &&
    (strm >> _tao_aggregate.spectrum);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::ConfigEntry &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.key.in ()) &&
    (strm << _tao_aggregate.value.in ()) &&
    (strm << _tao_aggregate.timestamp);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::ConfigEntry &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.key.out ()) &&
    (strm >> _tao_aggregate.value.out ()) &&
    (strm >> _tao_aggregate.timestamp);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_TypesModule_ConfigEntrySeq_CPP_
#define _TAO_CDR_OP_TypesModule_ConfigEntrySeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::ConfigEntrySeq &_tao_sequence
  )
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::ConfigEntrySeq &_tao_sequence
  )
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_TypesModule_ConfigEntrySeq_CPP_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::OuterData &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.inner) &&
    (strm << _tao_aggregate.count);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::OuterData &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.inner) &&
    (strm >> _tao_aggregate.count);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::ConfigSnapshot &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.entries) &&
    (strm << _tao_aggregate.version) &&
    (strm << _tao_aggregate.meta);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::ConfigSnapshot &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.entries) &&
    (strm >> _tao_aggregate.version) &&
    (strm >> _tao_aggregate.meta);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const BaseModule::BaseService_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    BaseModule::BaseService_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::BaseModule::BaseService RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const ConfigModule::Config_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    ConfigModule::Config_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::ConfigModule::Config RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DataServiceModule::ClientCallback_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DataServiceModule::ClientCallback_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::DataServiceModule::ClientCallback RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DataServiceModule::DataService_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DataServiceModule::DataService_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::DataServiceModule::DataService RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



