// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from 
// be/be_codegen.cpp:682

#ifndef _TAO_IDL_APPEXTENDEDS_CPP_
#define _TAO_IDL_APPEXTENDEDS_CPP_


#include "AppExtendedS.h"
#include "tao/PortableServer/Operation_Table_Dynamic_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Object_SArgument_T.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/TypeCode_SArg_Traits.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Basic_Arguments.h"
#include "tao/Object_Argument_T.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Var_Size_Argument_T.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"

#if !defined (__ACE_INLINE__)
#include "AppExtendedS.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_SENSORDATA__SARG_TRAITS_)
#define _TYPESMODULE_SENSORDATA__SARG_TRAITS_
  
  template<>
  class SArg_Traits<TypesModule::SensorData>
    : public
        Var_Size_SArg_Traits_T<
            TypesModule::SensorData,
            TAO::Any_Insert_Policy_Stream <TypesModule::SensorData>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGENTRY__SARG_TRAITS_)
#define _TYPESMODULE_CONFIGENTRY__SARG_TRAITS_
  
  template<>
  class SArg_Traits<TypesModule::ConfigEntry>
    : public
        Var_Size_SArg_Traits_T<
            TypesModule::ConfigEntry,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigEntry>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGSNAPSHOT__SARG_TRAITS_)
#define _TYPESMODULE_CONFIGSNAPSHOT__SARG_TRAITS_
  
  template<>
  class SArg_Traits<TypesModule::ConfigSnapshot>
    : public
        Var_Size_SArg_Traits_T<
            TypesModule::ConfigSnapshot,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigSnapshot>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_DATASERVICEMODULE_CLIENTCALLBACK__SARG_TRAITS_)
#define _DATASERVICEMODULE_CLIENTCALLBACK__SARG_TRAITS_
  
  template<>
  class  SArg_Traits<DataServiceModule::ClientCallback>
    : public
        Object_SArg_Traits_T<
            DataServiceModule::ClientCallback_ptr,
            DataServiceModule::ClientCallback_var,
            DataServiceModule::ClientCallback_out,
            TAO::Any_Insert_Policy_Stream <DataServiceModule::ClientCallback_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_SENSORDATA__ARG_TRAITS_)
#define _TYPESMODULE_SENSORDATA__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::SensorData>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::SensorData,
            TAO::Any_Insert_Policy_Stream <TypesModule::SensorData>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGENTRY__ARG_TRAITS_)
#define _TYPESMODULE_CONFIGENTRY__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::ConfigEntry>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::ConfigEntry,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigEntry>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:870

#if !defined (_TYPESMODULE_CONFIGSNAPSHOT__ARG_TRAITS_)
#define _TYPESMODULE_CONFIGSNAPSHOT__ARG_TRAITS_
  
  template<>
  class Arg_Traits<TypesModule::ConfigSnapshot>
    : public
        Var_Size_Arg_Traits_T<
            TypesModule::ConfigSnapshot,
            TAO::Any_Insert_Policy_Stream <TypesModule::ConfigSnapshot>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_DATASERVICEMODULE_CLIENTCALLBACK__ARG_TRAITS_)
#define _DATASERVICEMODULE_CLIENTCALLBACK__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<DataServiceModule::ClientCallback>
    : public
        Object_Arg_Traits_T<
            DataServiceModule::ClientCallback_ptr,
            DataServiceModule::ClientCallback_var,
            DataServiceModule::ClientCallback_out,
            TAO::Objref_Traits<DataServiceModule::ClientCallback>,
            TAO::Any_Insert_Policy_Stream <DataServiceModule::ClientCallback_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



static const TAO_operation_db_entry BaseModule_BaseService_operations [] = {
  {"ping", &POA_BaseModule::BaseService::ping_skel, 0},
  {"get_info", &POA_BaseModule::BaseService::get_info_skel, 0},
  {"_is_a", &POA_BaseModule::BaseService::_is_a_skel, 0},
  {"_non_existent", &POA_BaseModule::BaseService::_non_existent_skel, 0},
  {"_component", &POA_BaseModule::BaseService::_component_skel, 0},
  {"_interface", &POA_BaseModule::BaseService::_interface_skel, 0},
  {"_repository_id", &POA_BaseModule::BaseService::_repository_id_skel, 0}
};

static const ::CORBA::Long _tao_BaseModule_BaseService_optable_size = sizeof (ACE_Hash_Map_Entry<const char *, TAO::Operation_Skeletons>) * (21);
static char _tao_BaseModule_BaseService_optable_pool [_tao_BaseModule_BaseService_optable_size];
static ACE_Static_Allocator_Base _tao_BaseModule_BaseService_allocator (_tao_BaseModule_BaseService_optable_pool, _tao_BaseModule_BaseService_optable_size);
static TAO_Dynamic_Hash_OpTable tao_BaseModule_BaseService_optable (
    BaseModule_BaseService_operations,
    7,
    14,
    &_tao_BaseModule_BaseService_allocator
  );


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:988

TAO::Collocation_Proxy_Broker *
BaseModule__TAO_BaseService_Proxy_Broker_Factory_function ( ::CORBA::Object_ptr)
{
  return reinterpret_cast<TAO::Collocation_Proxy_Broker *> (0xdead); // Dummy
}

int
BaseModule__TAO_BaseService_Proxy_Broker_Factory_Initializer (size_t)
{
  BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer = 
    BaseModule__TAO_BaseService_Proxy_Broker_Factory_function;
  
  return 0;
}

static int
BaseModule__TAO_BaseService_Proxy_Broker_Stub_Factory_Initializer_Scarecrow =
  BaseModule__TAO_BaseService_Proxy_Broker_Factory_Initializer (
      reinterpret_cast<size_t> (BaseModule__TAO_BaseService_Proxy_Broker_Factory_Initializer)
    );

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:103

POA_BaseModule::BaseService::BaseService (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_BaseModule_BaseService_optable;
}

POA_BaseModule::BaseService::BaseService (const BaseService& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs)
{
}

POA_BaseModule::BaseService::~BaseService (void)
{
}
namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class ping_BaseService
    : public TAO::Upcall_Command
  {
  public:
    inline ping_BaseService (
      POA_BaseModule::BaseService * servant)
      : servant_ (servant)
    {
    }
    
    virtual void execute (void)
    {
      this->servant_->ping ();
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_BaseModule::BaseService::ping_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);

  ping_BaseService command (
    impl);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class get_info_BaseService
    : public TAO::Upcall_Command
  {
  public:
    inline get_info_BaseService (
      POA_BaseModule::BaseService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< char *> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_->get_info ();
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_BaseModule::BaseService::get_info_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< char *>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);

  get_info_BaseService command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:169

namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _is_a_BaseService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _is_a_BaseService_Upcall_Command (
      POA_BaseModule::BaseService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_-> _is_a (
          arg_1);
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_BaseModule::BaseService::_is_a_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_repository_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_repository_id
    };
  
  static size_t const nargs = 2;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);
  
  _is_a_BaseService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _non_existent_BaseService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _non_existent_BaseService_Upcall_Command (
      POA_BaseModule::BaseService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _non_existent ();
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_BaseModule::BaseService::_non_existent_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);
  
  _non_existent_BaseService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}
namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _repository_id_BaseService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _repository_id_BaseService_Upcall_Command (
      POA_BaseModule::BaseService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< char *> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _repository_id ();
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_BaseModule::BaseService::_repository_id_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< char *>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);
  
  _repository_id_BaseService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:512

void POA_BaseModule::BaseService::_interface_skel (
    TAO_ServerRequest & server_request, 
    void * /* servant_upcall */,
    void * servant)
{
  TAO_IFR_Client_Adapter *_tao_adapter =
    ACE_Dynamic_Service<TAO_IFR_Client_Adapter>::instance (
        TAO_ORB_Core::ifr_client_adapter_name ()
      );
    
  if (!_tao_adapter)
    {
      throw ::CORBA::INTF_REPOS (::CORBA::OMGVMCID | 1, ::CORBA::COMPLETED_NO);
    }
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);
  ::CORBA::InterfaceDef_ptr _tao_retval = impl->_get_interface ();
  server_request.init_reply ();
  TAO_OutputCDR &_tao_out = *server_request.outgoing ();
  
  ::CORBA::Boolean const _tao_result =
    _tao_adapter->interfacedef_cdr_insert (_tao_out, _tao_retval);
  
  _tao_adapter->dispose (_tao_retval);
  
  if (!_tao_result)
    {
      throw ::CORBA::MARSHAL ();
    }
}

namespace POA_BaseModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _get_component_BaseService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _get_component_BaseService_Upcall_Command (
      POA_BaseModule::BaseService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Object>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Object> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _get_component ();
    }
  
  private:
    POA_BaseModule::BaseService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_BaseModule::BaseService::_component_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant
  )
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_BaseModule::BaseService * const impl =
    static_cast<POA_BaseModule::BaseService *> (servant);
  
  _get_component_BaseService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

::CORBA::Boolean POA_BaseModule::BaseService::_is_a (const char* value)
{
  return
    (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_BaseModule::BaseService::_interface_repository_id (void) const
{
  return "IDL:BaseModule/BaseService:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:930

void POA_BaseModule::BaseService::_dispatch (TAO_ServerRequest & req, void * servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:856

BaseModule::BaseService *
POA_BaseModule::BaseService::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();
  
  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();
  
  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0
    );
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();
  
  typedef ::BaseModule::BaseService STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer
      );
}

static const TAO_operation_db_entry ConfigModule_Config_operations [] = {
  {"ping", &POA_ConfigModule::Config::ping_skel, 0},
  {"get_info", &POA_ConfigModule::Config::get_info_skel, 0},
  {"get_value", &POA_ConfigModule::Config::get_value_skel, 0},
  {"set_value", &POA_ConfigModule::Config::set_value_skel, 0},
  {"try_get", &POA_ConfigModule::Config::try_get_skel, 0},
  {"get_counter", &POA_ConfigModule::Config::get_counter_skel, 0},
  {"set_entry", &POA_ConfigModule::Config::set_entry_skel, 0},
  {"get_entry", &POA_ConfigModule::Config::get_entry_skel, 0},
  {"_is_a", &POA_ConfigModule::Config::_is_a_skel, 0},
  {"_non_existent", &POA_ConfigModule::Config::_non_existent_skel, 0},
  {"_component", &POA_ConfigModule::Config::_component_skel, 0},
  {"_interface", &POA_ConfigModule::Config::_interface_skel, 0},
  {"_repository_id", &POA_ConfigModule::Config::_repository_id_skel, 0}
};

static const ::CORBA::Long _tao_ConfigModule_Config_optable_size = sizeof (ACE_Hash_Map_Entry<const char *, TAO::Operation_Skeletons>) * (39);
static char _tao_ConfigModule_Config_optable_pool [_tao_ConfigModule_Config_optable_size];
static ACE_Static_Allocator_Base _tao_ConfigModule_Config_allocator (_tao_ConfigModule_Config_optable_pool, _tao_ConfigModule_Config_optable_size);
static TAO_Dynamic_Hash_OpTable tao_ConfigModule_Config_optable (
    ConfigModule_Config_operations,
    13,
    26,
    &_tao_ConfigModule_Config_allocator
  );


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:988

TAO::Collocation_Proxy_Broker *
ConfigModule__TAO_Config_Proxy_Broker_Factory_function ( ::CORBA::Object_ptr)
{
  return reinterpret_cast<TAO::Collocation_Proxy_Broker *> (0xdead); // Dummy
}

int
ConfigModule__TAO_Config_Proxy_Broker_Factory_Initializer (size_t)
{
  ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer = 
    ConfigModule__TAO_Config_Proxy_Broker_Factory_function;
  
  return 0;
}

static int
ConfigModule__TAO_Config_Proxy_Broker_Stub_Factory_Initializer_Scarecrow =
  ConfigModule__TAO_Config_Proxy_Broker_Factory_Initializer (
      reinterpret_cast<size_t> (ConfigModule__TAO_Config_Proxy_Broker_Factory_Initializer)
    );

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:103

POA_ConfigModule::Config::Config (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_ConfigModule_Config_optable;
}

POA_ConfigModule::Config::Config (const Config& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_BaseModule::BaseService (rhs)
{
}

POA_ConfigModule::Config::~Config (void)
{
}
namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class get_value_Config
    : public TAO::Upcall_Command
  {
  public:
    inline get_value_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< char *>::out_arg_type arg_2 =
        TAO::Portable_Server::get_out_arg< char *> (
          this->operation_details_,
          this->args_,
          2);
        
      this->servant_->get_value (
        arg_1
        , arg_2);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::get_value_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_key;
  TAO::SArg_Traits< char *>::out_arg_val _tao_value;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_key,
      &_tao_value
    };
  
  static size_t const nargs = 3;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  get_value_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class set_value_Config
    : public TAO::Upcall_Command
  {
  public:
    inline set_value_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< char *>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          2);
        
      this->servant_->set_value (
        arg_1
        , arg_2);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::set_value_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_key;
  TAO::SArg_Traits< char *>::in_arg_val _tao_value;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_key,
      &_tao_value
    };
  
  static size_t const nargs = 3;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  set_value_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class try_get_Config
    : public TAO::Upcall_Command
  {
  public:
    inline try_get_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< char *>::inout_arg_type arg_2 =
        TAO::Portable_Server::get_inout_arg< char *> (
          this->operation_details_,
          this->args_,
          2);
        
      retval =
        this->servant_->try_get (
          arg_1
          , arg_2);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::try_get_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_key;
  TAO::SArg_Traits< char *>::inout_arg_val _tao_value;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_key,
      &_tao_value
    };
  
  static size_t const nargs = 3;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  try_get_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class get_counter_Config
    : public TAO::Upcall_Command
  {
  public:
    inline get_counter_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::out_arg_type arg_1 =
        TAO::Portable_Server::get_out_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->get_counter (
          arg_1);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::get_counter_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::CORBA::Long>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::out_arg_val _tao_current;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_current
    };
  
  static size_t const nargs = 2;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  get_counter_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class set_entry_Config
    : public TAO::Upcall_Command
  {
  public:
    inline set_entry_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::ConfigEntry>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TypesModule::ConfigEntry> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->set_entry (
        arg_1);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::set_entry_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::TypesModule::ConfigEntry>::in_arg_val _tao_e;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_e
    };
  
  static size_t const nargs = 2;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  set_entry_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class get_entry_Config
    : public TAO::Upcall_Command
  {
  public:
    inline get_entry_Config (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::ConfigEntry>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TypesModule::ConfigEntry> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->get_entry (
          arg_1);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_ConfigModule::Config::get_entry_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::TypesModule::ConfigEntry>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_key;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_key
    };
  
  static size_t const nargs = 2;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);

  get_entry_Config command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:169

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _is_a_Config_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _is_a_Config_Upcall_Command (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_-> _is_a (
          arg_1);
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_ConfigModule::Config::_is_a_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_repository_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_repository_id
    };
  
  static size_t const nargs = 2;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);
  
  _is_a_Config_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _non_existent_Config_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _non_existent_Config_Upcall_Command (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _non_existent ();
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_ConfigModule::Config::_non_existent_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);
  
  _non_existent_Config_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}
namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _repository_id_Config_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _repository_id_Config_Upcall_Command (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< char *> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _repository_id ();
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_ConfigModule::Config::_repository_id_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< char *>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);
  
  _repository_id_Config_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:512

void POA_ConfigModule::Config::_interface_skel (
    TAO_ServerRequest & server_request, 
    void * /* servant_upcall */,
    void * servant)
{
  TAO_IFR_Client_Adapter *_tao_adapter =
    ACE_Dynamic_Service<TAO_IFR_Client_Adapter>::instance (
        TAO_ORB_Core::ifr_client_adapter_name ()
      );
    
  if (!_tao_adapter)
    {
      throw ::CORBA::INTF_REPOS (::CORBA::OMGVMCID | 1, ::CORBA::COMPLETED_NO);
    }
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);
  ::CORBA::InterfaceDef_ptr _tao_retval = impl->_get_interface ();
  server_request.init_reply ();
  TAO_OutputCDR &_tao_out = *server_request.outgoing ();
  
  ::CORBA::Boolean const _tao_result =
    _tao_adapter->interfacedef_cdr_insert (_tao_out, _tao_retval);
  
  _tao_adapter->dispose (_tao_retval);
  
  if (!_tao_result)
    {
      throw ::CORBA::MARSHAL ();
    }
}

namespace POA_ConfigModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _get_component_Config_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _get_component_Config_Upcall_Command (
      POA_ConfigModule::Config * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Object>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Object> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _get_component ();
    }
  
  private:
    POA_ConfigModule::Config * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_ConfigModule::Config::_component_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant
  )
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_ConfigModule::Config * const impl =
    static_cast<POA_ConfigModule::Config *> (servant);
  
  _get_component_Config_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

::CORBA::Boolean POA_ConfigModule::Config::_is_a (const char* value)
{
  return
    (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:ConfigModule/Config:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_ConfigModule::Config::_interface_repository_id (void) const
{
  return "IDL:ConfigModule/Config:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:930

void POA_ConfigModule::Config::_dispatch (TAO_ServerRequest & req, void * servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:856

ConfigModule::Config *
POA_ConfigModule::Config::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();
  
  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();
  
  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0
    );
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();
  
  typedef ::ConfigModule::Config STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer
      );
}

static const TAO_operation_db_entry DataServiceModule_ClientCallback_operations [] = {
  {"on_telemetry", &POA_DataServiceModule::ClientCallback::on_telemetry_skel, 0},
  {"on_config", &POA_DataServiceModule::ClientCallback::on_config_skel, 0},
  {"_is_a", &POA_DataServiceModule::ClientCallback::_is_a_skel, 0},
  {"_non_existent", &POA_DataServiceModule::ClientCallback::_non_existent_skel, 0},
  {"_component", &POA_DataServiceModule::ClientCallback::_component_skel, 0},
  {"_interface", &POA_DataServiceModule::ClientCallback::_interface_skel, 0},
  {"_repository_id", &POA_DataServiceModule::ClientCallback::_repository_id_skel, 0}
};

static const ::CORBA::Long _tao_DataServiceModule_ClientCallback_optable_size = sizeof (ACE_Hash_Map_Entry<const char *, TAO::Operation_Skeletons>) * (21);
static char _tao_DataServiceModule_ClientCallback_optable_pool [_tao_DataServiceModule_ClientCallback_optable_size];
static ACE_Static_Allocator_Base _tao_DataServiceModule_ClientCallback_allocator (_tao_DataServiceModule_ClientCallback_optable_pool, _tao_DataServiceModule_ClientCallback_optable_size);
static TAO_Dynamic_Hash_OpTable tao_DataServiceModule_ClientCallback_optable (
    DataServiceModule_ClientCallback_operations,
    7,
    14,
    &_tao_DataServiceModule_ClientCallback_allocator
  );


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:988

TAO::Collocation_Proxy_Broker *
DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function ( ::CORBA::Object_ptr)
{
  return reinterpret_cast<TAO::Collocation_Proxy_Broker *> (0xdead); // Dummy
}

int
DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_Initializer (size_t)
{
  DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer = 
    DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function;
  
  return 0;
}

static int
DataServiceModule__TAO_ClientCallback_Proxy_Broker_Stub_Factory_Initializer_Scarecrow =
  DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_Initializer (
      reinterpret_cast<size_t> (DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_Initializer)
    );

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:103

POA_DataServiceModule::ClientCallback::ClientCallback (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_DataServiceModule_ClientCallback_optable;
}

POA_DataServiceModule::ClientCallback::ClientCallback (const ClientCallback& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs)
{
}

POA_DataServiceModule::ClientCallback::~ClientCallback (void)
{
}
namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class on_telemetry_ClientCallback
    : public TAO::Upcall_Command
  {
  public:
    inline on_telemetry_ClientCallback (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::SensorData>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TypesModule::SensorData> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->on_telemetry (
        arg_1);
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::ClientCallback::on_telemetry_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::TypesModule::SensorData>::in_arg_val _tao_data;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_data
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);

  on_telemetry_ClientCallback command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class on_config_ClientCallback
    : public TAO::Upcall_Command
  {
  public:
    inline on_config_ClientCallback (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::ConfigSnapshot>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TypesModule::ConfigSnapshot> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->on_config (
        arg_1);
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::ClientCallback::on_config_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::TypesModule::ConfigSnapshot>::in_arg_val _tao_cfg;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_cfg
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);

  on_config_ClientCallback command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:169

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _is_a_ClientCallback_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _is_a_ClientCallback_Upcall_Command (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_-> _is_a (
          arg_1);
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::ClientCallback::_is_a_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_repository_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_repository_id
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);
  
  _is_a_ClientCallback_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _non_existent_ClientCallback_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _non_existent_ClientCallback_Upcall_Command (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _non_existent ();
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::ClientCallback::_non_existent_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);
  
  _non_existent_ClientCallback_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}
namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _repository_id_ClientCallback_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _repository_id_ClientCallback_Upcall_Command (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< char *> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _repository_id ();
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::ClientCallback::_repository_id_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< char *>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);
  
  _repository_id_ClientCallback_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:512

void POA_DataServiceModule::ClientCallback::_interface_skel (
    TAO_ServerRequest & server_request, 
    void * /* servant_upcall */,
    void * servant)
{
  TAO_IFR_Client_Adapter *_tao_adapter =
    ACE_Dynamic_Service<TAO_IFR_Client_Adapter>::instance (
        TAO_ORB_Core::ifr_client_adapter_name ()
      );
    
  if (!_tao_adapter)
    {
      throw ::CORBA::INTF_REPOS (::CORBA::OMGVMCID | 1, ::CORBA::COMPLETED_NO);
    }
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);
  ::CORBA::InterfaceDef_ptr _tao_retval = impl->_get_interface ();
  server_request.init_reply ();
  TAO_OutputCDR &_tao_out = *server_request.outgoing ();
  
  ::CORBA::Boolean const _tao_result =
    _tao_adapter->interfacedef_cdr_insert (_tao_out, _tao_retval);
  
  _tao_adapter->dispose (_tao_retval);
  
  if (!_tao_result)
    {
      throw ::CORBA::MARSHAL ();
    }
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _get_component_ClientCallback_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _get_component_ClientCallback_Upcall_Command (
      POA_DataServiceModule::ClientCallback * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Object>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Object> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _get_component ();
    }
  
  private:
    POA_DataServiceModule::ClientCallback * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::ClientCallback::_component_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant
  )
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::ClientCallback * const impl =
    static_cast<POA_DataServiceModule::ClientCallback *> (servant);
  
  _get_component_ClientCallback_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

::CORBA::Boolean POA_DataServiceModule::ClientCallback::_is_a (const char* value)
{
  return
    (
      !ACE_OS::strcmp (
          value,
          "IDL:DataServiceModule/ClientCallback:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_DataServiceModule::ClientCallback::_interface_repository_id (void) const
{
  return "IDL:DataServiceModule/ClientCallback:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:930

void POA_DataServiceModule::ClientCallback::_dispatch (TAO_ServerRequest & req, void * servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:856

DataServiceModule::ClientCallback *
POA_DataServiceModule::ClientCallback::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();
  
  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();
  
  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0
    );
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();
  
  typedef ::DataServiceModule::ClientCallback STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer
      );
}

static const TAO_operation_db_entry DataServiceModule_DataService_operations [] = {
  {"ping", &POA_DataServiceModule::DataService::ping_skel, 0},
  {"get_info", &POA_DataServiceModule::DataService::get_info_skel, 0},
  {"register_client", &POA_DataServiceModule::DataService::register_client_skel, 0},
  {"submit_sensor", &POA_DataServiceModule::DataService::submit_sensor_skel, 0},
  {"get_sensor", &POA_DataServiceModule::DataService::get_sensor_skel, 0},
  {"register_callback", &POA_DataServiceModule::DataService::register_callback_skel, 0},
  {"_is_a", &POA_DataServiceModule::DataService::_is_a_skel, 0},
  {"_non_existent", &POA_DataServiceModule::DataService::_non_existent_skel, 0},
  {"_component", &POA_DataServiceModule::DataService::_component_skel, 0},
  {"_interface", &POA_DataServiceModule::DataService::_interface_skel, 0},
  {"_repository_id", &POA_DataServiceModule::DataService::_repository_id_skel, 0}
};

static const ::CORBA::Long _tao_DataServiceModule_DataService_optable_size = sizeof (ACE_Hash_Map_Entry<const char *, TAO::Operation_Skeletons>) * (33);
static char _tao_DataServiceModule_DataService_optable_pool [_tao_DataServiceModule_DataService_optable_size];
static ACE_Static_Allocator_Base _tao_DataServiceModule_DataService_allocator (_tao_DataServiceModule_DataService_optable_pool, _tao_DataServiceModule_DataService_optable_size);
static TAO_Dynamic_Hash_OpTable tao_DataServiceModule_DataService_optable (
    DataServiceModule_DataService_operations,
    11,
    22,
    &_tao_DataServiceModule_DataService_allocator
  );


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:988

TAO::Collocation_Proxy_Broker *
DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function ( ::CORBA::Object_ptr)
{
  return reinterpret_cast<TAO::Collocation_Proxy_Broker *> (0xdead); // Dummy
}

int
DataServiceModule__TAO_DataService_Proxy_Broker_Factory_Initializer (size_t)
{
  DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer = 
    DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function;
  
  return 0;
}

static int
DataServiceModule__TAO_DataService_Proxy_Broker_Stub_Factory_Initializer_Scarecrow =
  DataServiceModule__TAO_DataService_Proxy_Broker_Factory_Initializer (
      reinterpret_cast<size_t> (DataServiceModule__TAO_DataService_Proxy_Broker_Factory_Initializer)
    );

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:103

POA_DataServiceModule::DataService::DataService (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_DataServiceModule_DataService_optable;
}

POA_DataServiceModule::DataService::DataService (const DataService& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_BaseModule::BaseService (rhs)
{
}

POA_DataServiceModule::DataService::~DataService (void)
{
}
namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class register_client_DataService
    : public TAO::Upcall_Command
  {
  public:
    inline register_client_DataService (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->register_client (
        arg_1);
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::DataService::register_client_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_client_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_client_id
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);

  register_client_DataService command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class submit_sensor_DataService
    : public TAO::Upcall_Command
  {
  public:
    inline submit_sensor_DataService (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::SensorData>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TypesModule::SensorData> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->submit_sensor (
        arg_1);
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::DataService::submit_sensor_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::TypesModule::SensorData>::in_arg_val _tao_data;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_data
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);

  submit_sensor_DataService command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class get_sensor_DataService
    : public TAO::Upcall_Command
  {
  public:
    inline get_sensor_DataService (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TypesModule::SensorData>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TypesModule::SensorData> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->get_sensor (
          arg_1);
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::DataService::get_sensor_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::TypesModule::SensorData>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_id
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);

  get_sensor_DataService command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class register_callback_DataService
    : public TAO::Upcall_Command
  {
  public:
    inline register_callback_DataService (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::DataServiceModule::ClientCallback>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::DataServiceModule::ClientCallback> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->register_callback (
        arg_1);
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


// TAO_IDL - Generated from 
// be/be_visitor_operation/operation_ss.cpp:190

void POA_DataServiceModule::DataService::register_callback_skel (
    TAO_ServerRequest & server_request,
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::DataServiceModule::ClientCallback>::in_arg_val _tao_cb;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_cb
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);

  register_callback_DataService command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:169

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _is_a_DataService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _is_a_DataService_Upcall_Command (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< char *>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< char *> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_-> _is_a (
          arg_1);
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::DataService::_is_a_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  TAO::SArg_Traits< char *>::in_arg_val _tao_repository_id;
  
  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_repository_id
    };
  
  static size_t const nargs = 2;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);
  
  _is_a_DataService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _non_existent_DataService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _non_existent_DataService_Upcall_Command (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::ACE_InputCDR::to_boolean> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _non_existent ();
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::DataService::_non_existent_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);
  
  _non_existent_DataService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}
namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _repository_id_DataService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _repository_id_DataService_Upcall_Command (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< char *>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< char *> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _repository_id ();
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::DataService::_repository_id_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< char *>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);
  
  _repository_id_DataService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

// TAO_IDL - Generated from 
// be/be_visitor_interface/interface_ss.cpp:512

void POA_DataServiceModule::DataService::_interface_skel (
    TAO_ServerRequest & server_request, 
    void * /* servant_upcall */,
    void * servant)
{
  TAO_IFR_Client_Adapter *_tao_adapter =
    ACE_Dynamic_Service<TAO_IFR_Client_Adapter>::instance (
        TAO_ORB_Core::ifr_client_adapter_name ()
      );
    
  if (!_tao_adapter)
    {
      throw ::CORBA::INTF_REPOS (::CORBA::OMGVMCID | 1, ::CORBA::COMPLETED_NO);
    }
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);
  ::CORBA::InterfaceDef_ptr _tao_retval = impl->_get_interface ();
  server_request.init_reply ();
  TAO_OutputCDR &_tao_out = *server_request.outgoing ();
  
  ::CORBA::Boolean const _tao_result =
    _tao_adapter->interfacedef_cdr_insert (_tao_out, _tao_retval);
  
  _tao_adapter->dispose (_tao_retval);
  
  if (!_tao_result)
    {
      throw ::CORBA::MARSHAL ();
    }
}

namespace POA_DataServiceModule
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:136
  
  class _get_component_DataService_Upcall_Command
    : public TAO::Upcall_Command
  {
  public:
    inline _get_component_DataService_Upcall_Command (
      POA_DataServiceModule::DataService * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }
    
    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Object>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Object> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_-> _get_component ();
    }
  
  private:
    POA_DataServiceModule::DataService * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}


void POA_DataServiceModule::DataService::_component_skel (
    TAO_ServerRequest & server_request, 
    void * TAO_INTERCEPTOR (servant_upcall),
    void * servant
  )
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */
  
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
  
  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;
  
  POA_DataServiceModule::DataService * const impl =
    static_cast<POA_DataServiceModule::DataService *> (servant);
  
  _get_component_DataService_Upcall_Command command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}

::CORBA::Boolean POA_DataServiceModule::DataService::_is_a (const char* value)
{
  return
    (
      !ACE_OS::strcmp (
          value,
          "IDL:BaseModule/BaseService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DataServiceModule/DataService:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_DataServiceModule::DataService::_interface_repository_id (void) const
{
  return "IDL:DataServiceModule/DataService:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:930

void POA_DataServiceModule::DataService::_dispatch (TAO_ServerRequest & req, void * servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:856

DataServiceModule::DataService *
POA_DataServiceModule::DataService::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();
  
  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();
  
  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0
    );
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();
  
  typedef ::DataServiceModule::DataService STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer
      );
}

#endif /* ifndef */

