// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:134

#ifndef _TAO_IDL_APPEXTENDEDC_H_
#define _TAO_IDL_APPEXTENDEDC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "CommonTypedefsC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace TypesModule
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::StringSeq StringSeq;
  typedef CommonTypes::StringSeq_var StringSeq_var;
  typedef CommonTypes::StringSeq_out StringSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_StringSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::OctetSeq OctetSeq;
  typedef CommonTypes::OctetSeq_var OctetSeq_var;
  typedef CommonTypes::OctetSeq_out OctetSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_OctetSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::LongSeq LongSeq;
  typedef CommonTypes::LongSeq_var LongSeq_var;
  typedef CommonTypes::LongSeq_out LongSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_LongSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::DoubleSeq DoubleSeq;
  typedef CommonTypes::DoubleSeq_var DoubleSeq_var;
  typedef CommonTypes::DoubleSeq_out DoubleSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DoubleSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::KvSeq KvSeq;
  typedef CommonTypes::KvSeq_var KvSeq_var;
  typedef CommonTypes::KvSeq_out KvSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_KvSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::MetricSeq MetricSeq;
  typedef CommonTypes::MetricSeq_var MetricSeq_var;
  typedef CommonTypes::MetricSeq_out MetricSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_MetricSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typedef/typedef_ch.cpp:472
  
  typedef CommonTypes::InnerDataSeq InnerDataSeq;
  typedef CommonTypes::InnerDataSeq_var InnerDataSeq_var;
  typedef CommonTypes::InnerDataSeq_out InnerDataSeq_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_InnerDataSeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Sample;
  
  typedef
    TAO_Var_Var_T<
        Sample
      >
    Sample_var;
  
  typedef
    TAO_Out_T<
        Sample
      >
    Sample_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Sample
  {
    typedef Sample_var _var_type;
    typedef Sample_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long t_ms;
    ::CORBA::Double reading;
    CommonTypes::OctetSeq payload;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Sample;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_TYPESMODULE_SAMPLESEQ_CH_)
#define _TYPESMODULE_SAMPLESEQ_CH_
  
  class SampleSeq;
  
  typedef
    TAO_VarSeq_Var_T<
        SampleSeq
      >
    SampleSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        SampleSeq
      >
    SampleSeq_out;
  
  class  SampleSeq
    : public
        TAO::unbounded_value_sequence<
            Sample
          >
  {
  public:
    SampleSeq (void);
    SampleSeq ( ::CORBA::ULong max);
    SampleSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      Sample* buffer, 
      ::CORBA::Boolean release = false);
    SampleSeq (const SampleSeq &);
    virtual ~SampleSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef SampleSeq_var _var_type;
    typedef SampleSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SampleSeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Meta;
  
  typedef
    TAO_Var_Var_T<
        Meta
      >
    Meta_var;
  
  typedef
    TAO_Out_T<
        Meta
      >
    Meta_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Meta
  {
    typedef Meta_var _var_type;
    typedef Meta_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long source_id;
    TAO::String_Manager source_name;
    CommonTypes::StringSeq tags;
    CommonTypes::KvSeq attributes;
    CommonTypes::Location loc;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Meta;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SensorData;
  
  typedef
    TAO_Var_Var_T<
        SensorData
      >
    SensorData_var;
  
  typedef
    TAO_Out_T<
        SensorData
      >
    SensorData_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SensorData
  {
    typedef SensorData_var _var_type;
    typedef SensorData_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long id;
    TAO::String_Manager name;
    ::CORBA::Double value;
    TypesModule::Meta meta;
    CommonTypes::MetricSeq metrics;
    TypesModule::SampleSeq samples;
    CommonTypes::LongSeq histogram;
    CommonTypes::DoubleSeq spectrum;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SensorData;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ConfigEntry;
  
  typedef
    TAO_Var_Var_T<
        ConfigEntry
      >
    ConfigEntry_var;
  
  typedef
    TAO_Out_T<
        ConfigEntry
      >
    ConfigEntry_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ConfigEntry
  {
    typedef ConfigEntry_var _var_type;
    typedef ConfigEntry_out _out_type;
    
    static void _tao_any_destructor (void *);
    TAO::String_Manager key;
    TAO::String_Manager value;
    ::CORBA::Long timestamp;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ConfigEntry;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_TYPESMODULE_CONFIGENTRYSEQ_CH_)
#define _TYPESMODULE_CONFIGENTRYSEQ_CH_
  
  class ConfigEntrySeq;
  
  typedef
    TAO_VarSeq_Var_T<
        ConfigEntrySeq
      >
    ConfigEntrySeq_var;
  
  typedef
    TAO_Seq_Out_T<
        ConfigEntrySeq
      >
    ConfigEntrySeq_out;
  
  class  ConfigEntrySeq
    : public
        TAO::unbounded_value_sequence<
            ConfigEntry
          >
  {
  public:
    ConfigEntrySeq (void);
    ConfigEntrySeq ( ::CORBA::ULong max);
    ConfigEntrySeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ConfigEntry* buffer, 
      ::CORBA::Boolean release = false);
    ConfigEntrySeq (const ConfigEntrySeq &);
    virtual ~ConfigEntrySeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef ConfigEntrySeq_var _var_type;
    typedef ConfigEntrySeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ConfigEntrySeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct OuterData;
  
  typedef
    TAO_Var_Var_T<
        OuterData
      >
    OuterData_var;
  
  typedef
    TAO_Out_T<
        OuterData
      >
    OuterData_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  OuterData
  {
    typedef OuterData_var _var_type;
    typedef OuterData_out _out_type;
    
    static void _tao_any_destructor (void *);
    CommonTypes::InnerData inner;
    ::CORBA::Long count;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_OuterData;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ConfigSnapshot;
  
  typedef
    TAO_Var_Var_T<
        ConfigSnapshot
      >
    ConfigSnapshot_var;
  
  typedef
    TAO_Out_T<
        ConfigSnapshot
      >
    ConfigSnapshot_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ConfigSnapshot
  {
    typedef ConfigSnapshot_var _var_type;
    typedef ConfigSnapshot_out _out_type;
    
    static void _tao_any_destructor (void *);
    TypesModule::ConfigEntrySeq entries;
    ::CORBA::Long version;
    TypesModule::OuterData meta;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ConfigSnapshot;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module TypesModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace BaseModule
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_BASEMODULE_BASESERVICE__VAR_OUT_CH_)
#define _BASEMODULE_BASESERVICE__VAR_OUT_CH_
  
  class BaseService;
  typedef BaseService *BaseService_ptr;
  
  typedef
    TAO_Objref_Var_T<
        BaseService
      >
    BaseService_var;
  
  typedef
    TAO_Objref_Out_T<
        BaseService
      >
    BaseService_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  BaseService
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<BaseService>;
    typedef BaseService_ptr _ptr_type;
    typedef BaseService_var _var_type;
    typedef BaseService_out _out_type;
    
    // The static operations.
    static BaseService_ptr _duplicate (BaseService_ptr obj);
    
    static void _tao_release (BaseService_ptr obj);
    
    static BaseService_ptr _narrow (::CORBA::Object_ptr obj);
    static BaseService_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static BaseService_ptr _nil (void)
    {
      return static_cast<BaseService_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    ping (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual char *
    get_info (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_BaseService_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    BaseService (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void BaseModule_BaseService_setup_collocation (void);
    
    // Concrete non-local interface only.
    BaseService (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    BaseService (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~BaseService (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    BaseService (const BaseService &);
    
    void operator= (const BaseService &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_BaseService;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module BaseModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace ConfigModule
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_CONFIGMODULE_CONFIG__VAR_OUT_CH_)
#define _CONFIGMODULE_CONFIG__VAR_OUT_CH_
  
  class Config;
  typedef Config *Config_ptr;
  
  typedef
    TAO_Objref_Var_T<
        Config
      >
    Config_var;
  
  typedef
    TAO_Objref_Out_T<
        Config
      >
    Config_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  Config
    : public virtual ::BaseModule::BaseService
  {
  public:
    friend class TAO::Narrow_Utils<Config>;
    typedef Config_ptr _ptr_type;
    typedef Config_var _var_type;
    typedef Config_out _out_type;
    
    // The static operations.
    static Config_ptr _duplicate (Config_ptr obj);
    
    static void _tao_release (Config_ptr obj);
    
    static Config_ptr _narrow (::CORBA::Object_ptr obj);
    static Config_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Config_ptr _nil (void)
    {
      return static_cast<Config_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    get_value (
      const char * key,
      ::CORBA::String_out value);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    set_value (
      const char * key,
      const char * value);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Boolean
    try_get (
      const char * key,
      char *& value);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Long
    get_counter (
      ::CORBA::Long_out current);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    set_entry (
      const ::TypesModule::ConfigEntry & e);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::TypesModule::ConfigEntry *
    get_entry (
      const char * key);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_Config_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    Config (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void ConfigModule_Config_setup_collocation (void);
    
    // Concrete non-local interface only.
    Config (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Config (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~Config (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    Config (const Config &);
    
    void operator= (const Config &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Config;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module ConfigModule

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace DataServiceModule
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_DATASERVICEMODULE_CLIENTCALLBACK__VAR_OUT_CH_)
#define _DATASERVICEMODULE_CLIENTCALLBACK__VAR_OUT_CH_
  
  class ClientCallback;
  typedef ClientCallback *ClientCallback_ptr;
  
  typedef
    TAO_Objref_Var_T<
        ClientCallback
      >
    ClientCallback_var;
  
  typedef
    TAO_Objref_Out_T<
        ClientCallback
      >
    ClientCallback_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  ClientCallback
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<ClientCallback>;
    typedef ClientCallback_ptr _ptr_type;
    typedef ClientCallback_var _var_type;
    typedef ClientCallback_out _out_type;
    
    // The static operations.
    static ClientCallback_ptr _duplicate (ClientCallback_ptr obj);
    
    static void _tao_release (ClientCallback_ptr obj);
    
    static ClientCallback_ptr _narrow (::CORBA::Object_ptr obj);
    static ClientCallback_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ClientCallback_ptr _nil (void)
    {
      return static_cast<ClientCallback_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    on_telemetry (
      const ::TypesModule::SensorData & data);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    on_config (
      const ::TypesModule::ConfigSnapshot & cfg);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_ClientCallback_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    ClientCallback (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void DataServiceModule_ClientCallback_setup_collocation (void);
    
    // Concrete non-local interface only.
    ClientCallback (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    ClientCallback (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~ClientCallback (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ClientCallback (const ClientCallback &);
    
    void operator= (const ClientCallback &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ClientCallback;
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_DATASERVICEMODULE_DATASERVICE__VAR_OUT_CH_)
#define _DATASERVICEMODULE_DATASERVICE__VAR_OUT_CH_
  
  class DataService;
  typedef DataService *DataService_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DataService
      >
    DataService_var;
  
  typedef
    TAO_Objref_Out_T<
        DataService
      >
    DataService_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  DataService
    : public virtual ::BaseModule::BaseService
  {
  public:
    friend class TAO::Narrow_Utils<DataService>;
    typedef DataService_ptr _ptr_type;
    typedef DataService_var _var_type;
    typedef DataService_out _out_type;
    
    // The static operations.
    static DataService_ptr _duplicate (DataService_ptr obj);
    
    static void _tao_release (DataService_ptr obj);
    
    static DataService_ptr _narrow (::CORBA::Object_ptr obj);
    static DataService_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataService_ptr _nil (void)
    {
      return static_cast<DataService_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    register_client (
      const char * client_id);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    submit_sensor (
      const ::TypesModule::SensorData & data);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::TypesModule::SensorData *
    get_sensor (
      ::CORBA::Long id);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    register_callback (
      ::DataServiceModule::ClientCallback_ptr cb);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_DataService_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    DataService (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void DataServiceModule_DataService_setup_collocation (void);
    
    // Concrete non-local interface only.
    DataService (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    DataService (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~DataService (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataService (const DataService &);
    
    void operator= (const DataService &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DataService;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module DataServiceModule

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*BaseModule__TAO_BaseService_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

extern 
TAO::Collocation_Proxy_Broker *
(*ConfigModule__TAO_Config_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

extern 
TAO::Collocation_Proxy_Broker *
(*DataServiceModule__TAO_ClientCallback_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

extern 
TAO::Collocation_Proxy_Broker *
(*DataServiceModule__TAO_DataService_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_BASEMODULE_BASESERVICE__TRAITS_)
#define _BASEMODULE_BASESERVICE__TRAITS_
  
  template<>
  struct  Objref_Traits< ::BaseModule::BaseService>
  {
    static ::BaseModule::BaseService_ptr duplicate (
        ::BaseModule::BaseService_ptr p
      );
    static void release (
        ::BaseModule::BaseService_ptr p
      );
    static ::BaseModule::BaseService_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::BaseModule::BaseService_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_CONFIGMODULE_CONFIG__TRAITS_)
#define _CONFIGMODULE_CONFIG__TRAITS_
  
  template<>
  struct  Objref_Traits< ::ConfigModule::Config>
  {
    static ::ConfigModule::Config_ptr duplicate (
        ::ConfigModule::Config_ptr p
      );
    static void release (
        ::ConfigModule::Config_ptr p
      );
    static ::ConfigModule::Config_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::ConfigModule::Config_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_DATASERVICEMODULE_CLIENTCALLBACK__TRAITS_)
#define _DATASERVICEMODULE_CLIENTCALLBACK__TRAITS_
  
  template<>
  struct  Objref_Traits< ::DataServiceModule::ClientCallback>
  {
    static ::DataServiceModule::ClientCallback_ptr duplicate (
        ::DataServiceModule::ClientCallback_ptr p
      );
    static void release (
        ::DataServiceModule::ClientCallback_ptr p
      );
    static ::DataServiceModule::ClientCallback_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DataServiceModule::ClientCallback_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_DATASERVICEMODULE_DATASERVICE__TRAITS_)
#define _DATASERVICEMODULE_DATASERVICE__TRAITS_
  
  template<>
  struct  Objref_Traits< ::DataServiceModule::DataService>
  {
    static ::DataServiceModule::DataService_ptr duplicate (
        ::DataServiceModule::DataService_ptr p
      );
    static void release (
        ::DataServiceModule::DataService_ptr p
      );
    static ::DataServiceModule::DataService_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DataServiceModule::DataService_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::Sample &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::Sample*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::Sample *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::Sample *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const TypesModule::SampleSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, TypesModule::SampleSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::SampleSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::SampleSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::Meta &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::Meta*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::Meta *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::Meta *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::SensorData &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::SensorData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::SensorData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::SensorData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::ConfigEntry &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::ConfigEntry*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::ConfigEntry *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::ConfigEntry *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const TypesModule::ConfigEntrySeq &); // copying version
 void operator<<= ( ::CORBA::Any &, TypesModule::ConfigEntrySeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::ConfigEntrySeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::ConfigEntrySeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::OuterData &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::OuterData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::OuterData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::OuterData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TypesModule::ConfigSnapshot &); // copying version
 void operator<<= (::CORBA::Any &, TypesModule::ConfigSnapshot*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TypesModule::ConfigSnapshot *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TypesModule::ConfigSnapshot *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace BaseModule
{
   void operator<<= ( ::CORBA::Any &, BaseService_ptr); // copying
   void operator<<= ( ::CORBA::Any &, BaseService_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, BaseService_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, BaseModule::BaseService_ptr); // copying
 void operator<<= (::CORBA::Any &, BaseModule::BaseService_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, BaseModule::BaseService_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ConfigModule
{
   void operator<<= ( ::CORBA::Any &, Config_ptr); // copying
   void operator<<= ( ::CORBA::Any &, Config_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Config_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, ConfigModule::Config_ptr); // copying
 void operator<<= (::CORBA::Any &, ConfigModule::Config_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ConfigModule::Config_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DataServiceModule
{
   void operator<<= ( ::CORBA::Any &, ClientCallback_ptr); // copying
   void operator<<= ( ::CORBA::Any &, ClientCallback_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ClientCallback_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, DataServiceModule::ClientCallback_ptr); // copying
 void operator<<= (::CORBA::Any &, DataServiceModule::ClientCallback_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DataServiceModule::ClientCallback_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DataServiceModule
{
   void operator<<= ( ::CORBA::Any &, DataService_ptr); // copying
   void operator<<= ( ::CORBA::Any &, DataService_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DataService_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, DataServiceModule::DataService_ptr); // copying
 void operator<<= (::CORBA::Any &, DataServiceModule::DataService_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DataServiceModule::DataService_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::Sample &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::Sample &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_TypesModule_SampleSeq_H_
#define _TAO_CDR_OP_TypesModule_SampleSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::SampleSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::SampleSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_TypesModule_SampleSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::Meta &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::Meta &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::SensorData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::SensorData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::ConfigEntry &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::ConfigEntry &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_TypesModule_ConfigEntrySeq_H_
#define _TAO_CDR_OP_TypesModule_ConfigEntrySeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TypesModule::ConfigEntrySeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TypesModule::ConfigEntrySeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_TypesModule_ConfigEntrySeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::OuterData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::OuterData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TypesModule::ConfigSnapshot &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TypesModule::ConfigSnapshot &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const BaseModule::BaseService_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, BaseModule::BaseService_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const ConfigModule::Config_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, ConfigModule::Config_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DataServiceModule::ClientCallback_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DataServiceModule::ClientCallback_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DataServiceModule::DataService_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DataServiceModule::DataService_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1452
#if defined (__ACE_INLINE__)
#include "AppExtendedC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


