// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:134

#ifndef _TAO_IDL_COMMONTYPEDEFSC_H_
#define _TAO_IDL_COMMONTYPEDEFSC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace CommonTypes
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_STRINGSEQ_CH_)
#define _COMMONTYPES_STRINGSEQ_CH_
  
  class StringSeq;
  
  typedef
    TAO_VarSeq_Var_T<
        StringSeq
      >
    StringSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        StringSeq
      >
    StringSeq_out;
  
  class  StringSeq
    : public
        TAO::unbounded_basic_string_sequence<char>
  {
  public:
    StringSeq (void);
    StringSeq ( ::CORBA::ULong max);
    StringSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer, 
      ::CORBA::Boolean release = false);
    StringSeq (const StringSeq &);
    virtual ~StringSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef StringSeq_var _var_type;
    typedef StringSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_StringSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_OCTETSEQ_CH_)
#define _COMMONTYPES_OCTETSEQ_CH_
  
  class OctetSeq;
  
  typedef
    TAO_FixedSeq_Var_T<
        OctetSeq
      >
    OctetSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        OctetSeq
      >
    OctetSeq_out;
  
  class  OctetSeq
    : public
        TAO::unbounded_value_sequence<
            ::CORBA::Octet
          >
  {
  public:
    OctetSeq (void);
    OctetSeq ( ::CORBA::ULong max);
    OctetSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Octet* buffer, 
      ::CORBA::Boolean release = false);
    OctetSeq (const OctetSeq &);
    virtual ~OctetSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef OctetSeq_var _var_type;
    typedef OctetSeq_out _out_type;
    
    

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    OctetSeq (
        ::CORBA::ULong length,
        const ACE_Message_Block* mb
      )
      : TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_OctetSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_LONGSEQ_CH_)
#define _COMMONTYPES_LONGSEQ_CH_
  
  class LongSeq;
  
  typedef
    TAO_FixedSeq_Var_T<
        LongSeq
      >
    LongSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        LongSeq
      >
    LongSeq_out;
  
  class  LongSeq
    : public
        TAO::unbounded_value_sequence<
            ::CORBA::Long
          >
  {
  public:
    LongSeq (void);
    LongSeq ( ::CORBA::ULong max);
    LongSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Long* buffer, 
      ::CORBA::Boolean release = false);
    LongSeq (const LongSeq &);
    virtual ~LongSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef LongSeq_var _var_type;
    typedef LongSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_LongSeq;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_DOUBLESEQ_CH_)
#define _COMMONTYPES_DOUBLESEQ_CH_
  
  class DoubleSeq;
  
  typedef
    TAO_FixedSeq_Var_T<
        DoubleSeq
      >
    DoubleSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        DoubleSeq
      >
    DoubleSeq_out;
  
  class  DoubleSeq
    : public
        TAO::unbounded_value_sequence<
            ::CORBA::Double
          >
  {
  public:
    DoubleSeq (void);
    DoubleSeq ( ::CORBA::ULong max);
    DoubleSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Double* buffer, 
      ::CORBA::Boolean release = false);
    DoubleSeq (const DoubleSeq &);
    virtual ~DoubleSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef DoubleSeq_var _var_type;
    typedef DoubleSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DoubleSeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Kv;
  
  typedef
    TAO_Var_Var_T<
        Kv
      >
    Kv_var;
  
  typedef
    TAO_Out_T<
        Kv
      >
    Kv_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Kv
  {
    typedef Kv_var _var_type;
    typedef Kv_out _out_type;
    
    static void _tao_any_destructor (void *);
    TAO::String_Manager k;
    TAO::String_Manager v;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Kv;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_KVSEQ_CH_)
#define _COMMONTYPES_KVSEQ_CH_
  
  class KvSeq;
  
  typedef
    TAO_VarSeq_Var_T<
        KvSeq
      >
    KvSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        KvSeq
      >
    KvSeq_out;
  
  class  KvSeq
    : public
        TAO::unbounded_value_sequence<
            Kv
          >
  {
  public:
    KvSeq (void);
    KvSeq ( ::CORBA::ULong max);
    KvSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      Kv* buffer, 
      ::CORBA::Boolean release = false);
    KvSeq (const KvSeq &);
    virtual ~KvSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef KvSeq_var _var_type;
    typedef KvSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_KvSeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Metric;
  
  typedef
    TAO_Var_Var_T<
        Metric
      >
    Metric_var;
  
  typedef
    TAO_Out_T<
        Metric
      >
    Metric_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Metric
  {
    typedef Metric_var _var_type;
    typedef Metric_out _out_type;
    
    static void _tao_any_destructor (void *);
    TAO::String_Manager name;
    ::CORBA::Double value;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Metric;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_METRICSEQ_CH_)
#define _COMMONTYPES_METRICSEQ_CH_
  
  class MetricSeq;
  
  typedef
    TAO_VarSeq_Var_T<
        MetricSeq
      >
    MetricSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        MetricSeq
      >
    MetricSeq_out;
  
  class  MetricSeq
    : public
        TAO::unbounded_value_sequence<
            Metric
          >
  {
  public:
    MetricSeq (void);
    MetricSeq ( ::CORBA::ULong max);
    MetricSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      Metric* buffer, 
      ::CORBA::Boolean release = false);
    MetricSeq (const MetricSeq &);
    virtual ~MetricSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef MetricSeq_var _var_type;
    typedef MetricSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_MetricSeq;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Location;
  
  typedef
    TAO_Fixed_Var_T<
        Location
      >
    Location_var;
  
  typedef
    Location &
    Location_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Location
  {
    typedef Location_var _var_type;
    typedef Location_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Double lat;
    ::CORBA::Double lon;
    ::CORBA::Double alt;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Location;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct InnerData;
  
  typedef
    TAO_Var_Var_T<
        InnerData
      >
    InnerData_var;
  
  typedef
    TAO_Out_T<
        InnerData
      >
    InnerData_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  InnerData
  {
    typedef InnerData_var _var_type;
    typedef InnerData_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long id;
    TAO::String_Manager tag;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_InnerData;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_COMMONTYPES_INNERDATASEQ_CH_)
#define _COMMONTYPES_INNERDATASEQ_CH_
  
  class InnerDataSeq;
  
  typedef
    TAO_VarSeq_Var_T<
        InnerDataSeq
      >
    InnerDataSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        InnerDataSeq
      >
    InnerDataSeq_out;
  
  class  InnerDataSeq
    : public
        TAO::unbounded_value_sequence<
            InnerData
          >
  {
  public:
    InnerDataSeq (void);
    InnerDataSeq ( ::CORBA::ULong max);
    InnerDataSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      InnerData* buffer, 
      ::CORBA::Boolean release = false);
    InnerDataSeq (const InnerDataSeq &);
    virtual ~InnerDataSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef InnerDataSeq_var _var_type;
    typedef InnerDataSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_InnerDataSeq;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module CommonTypes

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::StringSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::StringSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::StringSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::StringSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::OctetSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::OctetSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::OctetSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::OctetSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::LongSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::LongSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::LongSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::LongSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::DoubleSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::DoubleSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::DoubleSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::DoubleSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const CommonTypes::Kv &); // copying version
 void operator<<= (::CORBA::Any &, CommonTypes::Kv*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::Kv *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::Kv *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::KvSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::KvSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::KvSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::KvSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const CommonTypes::Metric &); // copying version
 void operator<<= (::CORBA::Any &, CommonTypes::Metric*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::Metric *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::Metric *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::MetricSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::MetricSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::MetricSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::MetricSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const CommonTypes::Location &); // copying version
 void operator<<= (::CORBA::Any &, CommonTypes::Location*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::Location *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::Location *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const CommonTypes::InnerData &); // copying version
 void operator<<= (::CORBA::Any &, CommonTypes::InnerData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::InnerData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::InnerData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const CommonTypes::InnerDataSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, CommonTypes::InnerDataSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, CommonTypes::InnerDataSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const CommonTypes::InnerDataSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_StringSeq_H_
#define _TAO_CDR_OP_CommonTypes_StringSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::StringSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::StringSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_StringSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_OctetSeq_H_
#define _TAO_CDR_OP_CommonTypes_OctetSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::OctetSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::OctetSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_OctetSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_LongSeq_H_
#define _TAO_CDR_OP_CommonTypes_LongSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::LongSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::LongSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_LongSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_DoubleSeq_H_
#define _TAO_CDR_OP_CommonTypes_DoubleSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::DoubleSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::DoubleSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_DoubleSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CommonTypes::Kv &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CommonTypes::Kv &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_KvSeq_H_
#define _TAO_CDR_OP_CommonTypes_KvSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::KvSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::KvSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_KvSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CommonTypes::Metric &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CommonTypes::Metric &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_MetricSeq_H_
#define _TAO_CDR_OP_CommonTypes_MetricSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::MetricSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::MetricSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_MetricSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CommonTypes::Location &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CommonTypes::Location &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const CommonTypes::InnerData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, CommonTypes::InnerData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_CommonTypes_InnerDataSeq_H_
#define _TAO_CDR_OP_CommonTypes_InnerDataSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CommonTypes::InnerDataSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CommonTypes::InnerDataSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_CommonTypes_InnerDataSeq_H_ */

// TAO_IDL - Generated from
// be/be_codegen.cpp:1452
#if defined (__ACE_INLINE__)
#include "CommonTypedefsC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


