// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:471

#ifndef _TAO_IDL_COMMONTYPEDEFSS_H_
#define _TAO_IDL_COMMONTYPEDEFSS_H_


#include "CommonTypedefsC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_CommonTypes
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module CommonTypes

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1514


#if defined (__ACE_INLINE__)
#include "CommonTypedefsS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

