// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:375


#include "HelloC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/Sequence_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/AnyTypeCode/Any_Dual_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Var_Size_Argument_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "HelloC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:620

#if !defined (_HELLOMODULE_LONGSEQ__ARG_TRAITS_)
#define _HELLOMODULE_LONGSEQ__ARG_TRAITS_
  
  template<>
  class Arg_Traits<HelloModule::LongSeq>
    : public
        Var_Size_Arg_Traits_T<
            HelloModule::LongSeq,
            TAO::Any_Insert_Policy_Stream <HelloModule::LongSeq>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_sequence/sequence_cs.cpp:65

#if !defined (_HELLOMODULE_LONGSEQ_CS_)
#define _HELLOMODULE_LONGSEQ_CS_

HelloModule::LongSeq::LongSeq (void)
{}

HelloModule::LongSeq::LongSeq (
    ::CORBA::ULong max
  )
  : TAO::unbounded_value_sequence<
        ::CORBA::Long
      >
    (max)
{}

HelloModule::LongSeq::LongSeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Long * buffer,
    ::CORBA::Boolean release
  )
  : TAO::unbounded_value_sequence<
        ::CORBA::Long
      >
    (max, length, buffer, release)
{}

HelloModule::LongSeq::LongSeq (
    const LongSeq &seq
  )
  : TAO::unbounded_value_sequence<
        ::CORBA::Long
      >
    (seq)
{}

HelloModule::LongSeq::~LongSeq (void)
{}

void HelloModule::LongSeq::_tao_any_destructor (
    void * _tao_void_pointer
  )
{
  LongSeq * _tao_tmp_pointer =
    static_cast<LongSeq *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_typecode/alias_typecode.cpp:50



// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:516


#ifndef _TAO_TYPECODE_HelloModule_LongSeq_GUARD
#define _TAO_TYPECODE_HelloModule_LongSeq_GUARD

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace TAO
{
  namespace TypeCode
  {
    namespace
    {
      TAO::TypeCode::Sequence< ::CORBA::TypeCode_ptr const *,
                              TAO::Null_RefCount_Policy>
        HelloModule_LongSeq_0 (
          ::CORBA::tk_sequence,
          &CORBA::_tc_long,
          0U);
        
      ::CORBA::TypeCode_ptr const tc_HelloModule_LongSeq_0 =
        &HelloModule_LongSeq_0;
    }
  }
}

TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_TYPECODE_HelloModule_LongSeq_GUARD */

static TAO::TypeCode::Alias<char const *,
                            ::CORBA::TypeCode_ptr const *,
                            TAO::Null_RefCount_Policy>
  _tao_tc_HelloModule_LongSeq (
    ::CORBA::tk_alias,
    "IDL:HelloModule/LongSeq:1.0",
    "LongSeq",
    &TAO::TypeCode::tc_HelloModule_LongSeq_0);
  
namespace HelloModule
{
  ::CORBA::TypeCode_ptr const _tc_LongSeq =
    &_tao_tc_HelloModule_LongSeq;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for HelloModule::Hello.

HelloModule::Hello_ptr
TAO::Objref_Traits<HelloModule::Hello>::duplicate (
    HelloModule::Hello_ptr p)
{
  return HelloModule::Hello::_duplicate (p);
}

void
TAO::Objref_Traits<HelloModule::Hello>::release (
    HelloModule::Hello_ptr p)
{
  ::CORBA::release (p);
}

HelloModule::Hello_ptr
TAO::Objref_Traits<HelloModule::Hello>::nil (void)
{
  return HelloModule::Hello::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<HelloModule::Hello>::marshal (
    const HelloModule::Hello_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char *
HelloModule::Hello::say_hello (
  const char * name)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Hello_Proxy_Broker_ == 0)
    {
      HelloModule_Hello_setup_collocation ();
    }
  
  TAO::Arg_Traits< char *>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_name (name);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_name
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "say_hello",
      9,
      this->the_TAO_Hello_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Long
HelloModule::Hello::add (
  ::CORBA::Long a,
  ::CORBA::Long b)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Hello_Proxy_Broker_ == 0)
    {
      HelloModule_Hello_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_a (a);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_b (b);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_a,
      &_tao_b
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "add",
      3,
      this->the_TAO_Hello_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Long
HelloModule::Hello::sum_ids (
  const ::HelloModule::LongSeq & ids)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Hello_Proxy_Broker_ == 0)
    {
      HelloModule_Hello_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::HelloModule::LongSeq>::in_arg_val _tao_ids (ids);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_ids
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "sum_ids",
      7,
      this->the_TAO_Hello_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
HelloModule::Hello::shutdown (void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Hello_Proxy_Broker_ == 0)
    {
      HelloModule_Hello_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "shutdown",
      8,
      this->the_TAO_Hello_Proxy_Broker_,
      TAO::TAO_ONEWAY_INVOCATION
    );
  
  _tao_call.invoke (0, 0);
}

HelloModule::Hello::Hello (void)
 : the_TAO_Hello_Proxy_Broker_ (0)
{
  this->HelloModule_Hello_setup_collocation ();
}

void
HelloModule::Hello::HelloModule_Hello_setup_collocation ()
{
  if (::HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Hello_Proxy_Broker_ =
        ::HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer (this);
    }
}

HelloModule::Hello::~Hello (void)
{}

void 
HelloModule::Hello::_tao_any_destructor (void *_tao_void_pointer)
{
  Hello *_tao_tmp_pointer =
    static_cast<Hello *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

HelloModule::Hello_ptr
HelloModule::Hello::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Hello>::narrow (
        _tao_objref,
        "IDL:HelloModule/Hello:1.0",
        HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer
      );
}

HelloModule::Hello_ptr
HelloModule::Hello::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Hello>::unchecked_narrow (
        _tao_objref,
        "IDL:HelloModule/Hello:1.0",
        HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer
      );
}

HelloModule::Hello_ptr
HelloModule::Hello::_duplicate (Hello_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
HelloModule::Hello::_tao_release (Hello_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
HelloModule::Hello::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:HelloModule/Hello:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* HelloModule::Hello::_interface_repository_id (void) const
{
  return "IDL:HelloModule/Hello:1.0";
}

::CORBA::Boolean
HelloModule::Hello::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_HelloModule_Hello (
    ::CORBA::tk_objref,
    "IDL:HelloModule/Hello:1.0",
    "Hello");
  
namespace HelloModule
{
  ::CORBA::TypeCode_ptr const _tc_Hello =
    &_tao_tc_HelloModule_Hello;
}



// TAO_IDL - Generated from 
// be/be_visitor_sequence/any_op_cs.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const HelloModule::LongSeq &_tao_elem
  )
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<HelloModule::LongSeq *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<HelloModule::LongSeq>::insert_copy (
        _tao_any,
        HelloModule::LongSeq::_tao_any_destructor,
        HelloModule::_tc_LongSeq,
        _tao_elem
      );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    HelloModule::LongSeq *_tao_elem
  )
{
  TAO::Any_Dual_Impl_T<HelloModule::LongSeq>::insert (
      _tao_any,
      HelloModule::LongSeq::_tao_any_destructor,
      HelloModule::_tc_LongSeq,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    HelloModule::LongSeq *&_tao_elem
  )
{
  return _tao_any >>= const_cast<
      const HelloModule::LongSeq *&> (
      _tao_elem
    );
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const HelloModule::LongSeq *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<HelloModule::LongSeq>::extract (
        _tao_any,
        HelloModule::LongSeq::_tao_any_destructor,
        HelloModule::_tc_LongSeq,
        _tao_elem
      );
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<HelloModule::Hello>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace HelloModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Hello_ptr _tao_elem)
  {
    Hello_ptr _tao_objptr =
      Hello::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Hello_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Hello>::insert (
        _tao_any,
        Hello::_tao_any_destructor,
        _tc_Hello,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Hello_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Hello>::extract (
          _tao_any,
          Hello::_tao_any_destructor,
          _tc_Hello,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    HelloModule::Hello_ptr _tao_elem)
{
  HelloModule::Hello_ptr _tao_objptr =
    HelloModule::Hello::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    HelloModule::Hello_ptr *_tao_elem)
{
  TAO::Any_Impl_T<HelloModule::Hello>::insert (
      _tao_any,
      HelloModule::Hello::_tao_any_destructor,
      HelloModule::_tc_Hello,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    HelloModule::Hello_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<HelloModule::Hello>::extract (
        _tao_any,
        HelloModule::Hello::_tao_any_destructor,
        HelloModule::_tc_Hello,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_cs.cpp:96
#if !defined _TAO_CDR_OP_HelloModule_LongSeq_CPP_
#define _TAO_CDR_OP_HelloModule_LongSeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HelloModule::LongSeq &_tao_sequence
  )
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HelloModule::LongSeq &_tao_sequence
  )
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_HelloModule_LongSeq_CPP_ */

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HelloModule::Hello_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HelloModule::Hello_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::HelloModule::Hello RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



