// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:134

#ifndef _TAO_IDL_HELLOC_H_
#define _TAO_IDL_HELLOC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace HelloModule
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_HELLOMODULE_LONGSEQ_CH_)
#define _HELLOMODULE_LONGSEQ_CH_
  
  class LongSeq;
  
  typedef
    TAO_FixedSeq_Var_T<
        LongSeq
      >
    LongSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        LongSeq
      >
    LongSeq_out;
  
  class  LongSeq
    : public
        TAO::unbounded_value_sequence<
            ::CORBA::Long
          >
  {
  public:
    LongSeq (void);
    LongSeq ( ::CORBA::ULong max);
    LongSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Long* buffer, 
      ::CORBA::Boolean release = false);
    LongSeq (const LongSeq &);
    virtual ~LongSeq (void);
    
    static void _tao_any_destructor (void *);
    
    typedef LongSeq_var _var_type;
    typedef LongSeq_out _out_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_LongSeq;
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_HELLOMODULE_HELLO__VAR_OUT_CH_)
#define _HELLOMODULE_HELLO__VAR_OUT_CH_
  
  class Hello;
  typedef Hello *Hello_ptr;
  
  typedef
    TAO_Objref_Var_T<
        Hello
      >
    Hello_var;
  
  typedef
    TAO_Objref_Out_T<
        Hello
      >
    Hello_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  Hello
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<Hello>;
    typedef Hello_ptr _ptr_type;
    typedef Hello_var _var_type;
    typedef Hello_out _out_type;
    
    // The static operations.
    static Hello_ptr _duplicate (Hello_ptr obj);
    
    static void _tao_release (Hello_ptr obj);
    
    static Hello_ptr _narrow (::CORBA::Object_ptr obj);
    static Hello_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Hello_ptr _nil (void)
    {
      return static_cast<Hello_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual char *
    say_hello (
      const char * name);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Long
    add (
      ::CORBA::Long a,
      ::CORBA::Long b);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Long
    sum_ids (
      const ::HelloModule::LongSeq & ids);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    shutdown (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_Hello_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    Hello (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void HelloModule_Hello_setup_collocation (void);
    
    // Concrete non-local interface only.
    Hello (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Hello (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~Hello (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    Hello (const Hello &);
    
    void operator= (const Hello &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Hello;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module HelloModule

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*HelloModule__TAO_Hello_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_HELLOMODULE_HELLO__TRAITS_)
#define _HELLOMODULE_HELLO__TRAITS_
  
  template<>
  struct  Objref_Traits< ::HelloModule::Hello>
  {
    static ::HelloModule::Hello_ptr duplicate (
        ::HelloModule::Hello_ptr p
      );
    static void release (
        ::HelloModule::Hello_ptr p
      );
    static ::HelloModule::Hello_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::HelloModule::Hello_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const HelloModule::LongSeq &); // copying version
 void operator<<= ( ::CORBA::Any &, HelloModule::LongSeq*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, HelloModule::LongSeq *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const HelloModule::LongSeq *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace HelloModule
{
   void operator<<= ( ::CORBA::Any &, Hello_ptr); // copying
   void operator<<= ( ::CORBA::Any &, Hello_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Hello_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, HelloModule::Hello_ptr); // copying
 void operator<<= (::CORBA::Any &, HelloModule::Hello_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, HelloModule::Hello_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_HelloModule_LongSeq_H_
#define _TAO_CDR_OP_HelloModule_LongSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HelloModule::LongSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HelloModule::LongSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_HelloModule_LongSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const HelloModule::Hello_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, HelloModule::Hello_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1452
#if defined (__ACE_INLINE__)
#include "HelloC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


