// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:375


#include "MathC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "MathC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for MathModule::Math.

MathModule::Math_ptr
TAO::Objref_Traits<MathModule::Math>::duplicate (
    MathModule::Math_ptr p)
{
  return MathModule::Math::_duplicate (p);
}

void
TAO::Objref_Traits<MathModule::Math>::release (
    MathModule::Math_ptr p)
{
  ::CORBA::release (p);
}

MathModule::Math_ptr
TAO::Objref_Traits<MathModule::Math>::nil (void)
{
  return MathModule::Math::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<MathModule::Math>::marshal (
    const MathModule::Math_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Long
MathModule::Math::add (
  ::CORBA::Long a,
  ::CORBA::Long b)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Math_Proxy_Broker_ == 0)
    {
      MathModule_Math_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_a (a);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_b (b);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_a,
      &_tao_b
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "add",
      3,
      this->the_TAO_Math_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::LongLong
MathModule::Math::multiply (
  ::CORBA::LongLong x,
  ::CORBA::LongLong y)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Math_Proxy_Broker_ == 0)
    {
      MathModule_Math_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::LongLong>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::LongLong>::in_arg_val _tao_x (x);
  TAO::Arg_Traits< ::CORBA::LongLong>::in_arg_val _tao_y (y);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_x,
      &_tao_y
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "multiply",
      8,
      this->the_TAO_Math_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Float
MathModule::Math::divide (
  ::CORBA::Float a,
  ::CORBA::Float b)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Math_Proxy_Broker_ == 0)
    {
      MathModule_Math_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Float>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Float>::in_arg_val _tao_a (a);
  TAO::Arg_Traits< ::CORBA::Float>::in_arg_val _tao_b (b);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_a,
      &_tao_b
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "divide",
      6,
      this->the_TAO_Math_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Double
MathModule::Math::power (
  ::CORBA::Double base,
  ::CORBA::Double exp)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Math_Proxy_Broker_ == 0)
    {
      MathModule_Math_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Double>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_base (base);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_exp (exp);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_base,
      &_tao_exp
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "power",
      5,
      this->the_TAO_Math_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::ULong
MathModule::Math::factorial (
  ::CORBA::UShort n)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Math_Proxy_Broker_ == 0)
    {
      MathModule_Math_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::ULong>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::UShort>::in_arg_val _tao_n (n);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_n
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "factorial",
      9,
      this->the_TAO_Math_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

MathModule::Math::Math (void)
 : the_TAO_Math_Proxy_Broker_ (0)
{
  this->MathModule_Math_setup_collocation ();
}

void
MathModule::Math::MathModule_Math_setup_collocation ()
{
  if (::MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Math_Proxy_Broker_ =
        ::MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer (this);
    }
}

MathModule::Math::~Math (void)
{}

void 
MathModule::Math::_tao_any_destructor (void *_tao_void_pointer)
{
  Math *_tao_tmp_pointer =
    static_cast<Math *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

MathModule::Math_ptr
MathModule::Math::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Math>::narrow (
        _tao_objref,
        "IDL:MathModule/Math:1.0",
        MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer
      );
}

MathModule::Math_ptr
MathModule::Math::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Math>::unchecked_narrow (
        _tao_objref,
        "IDL:MathModule/Math:1.0",
        MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer
      );
}

MathModule::Math_ptr
MathModule::Math::_duplicate (Math_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
MathModule::Math::_tao_release (Math_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
MathModule::Math::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:MathModule/Math:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* MathModule::Math::_interface_repository_id (void) const
{
  return "IDL:MathModule/Math:1.0";
}

::CORBA::Boolean
MathModule::Math::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_MathModule_Math (
    ::CORBA::tk_objref,
    "IDL:MathModule/Math:1.0",
    "Math");
  
namespace MathModule
{
  ::CORBA::TypeCode_ptr const _tc_Math =
    &_tao_tc_MathModule_Math;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<MathModule::Math>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace MathModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Math_ptr _tao_elem)
  {
    Math_ptr _tao_objptr =
      Math::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Math_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Math>::insert (
        _tao_any,
        Math::_tao_any_destructor,
        _tc_Math,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Math_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Math>::extract (
          _tao_any,
          Math::_tao_any_destructor,
          _tc_Math,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    MathModule::Math_ptr _tao_elem)
{
  MathModule::Math_ptr _tao_objptr =
    MathModule::Math::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    MathModule::Math_ptr *_tao_elem)
{
  TAO::Any_Impl_T<MathModule::Math>::insert (
      _tao_any,
      MathModule::Math::_tao_any_destructor,
      MathModule::_tc_Math,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    MathModule::Math_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<MathModule::Math>::extract (
        _tao_any,
        MathModule::Math::_tao_any_destructor,
        MathModule::_tc_Math,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MathModule::Math_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MathModule::Math_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::MathModule::Math RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        MathModule__TAO_Math_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



