// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:375


#include "ServiceC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "ServiceC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for ServiceModule::Service.

ServiceModule::Service_ptr
TAO::Objref_Traits<ServiceModule::Service>::duplicate (
    ServiceModule::Service_ptr p)
{
  return ServiceModule::Service::_duplicate (p);
}

void
TAO::Objref_Traits<ServiceModule::Service>::release (
    ServiceModule::Service_ptr p)
{
  ::CORBA::release (p);
}

ServiceModule::Service_ptr
TAO::Objref_Traits<ServiceModule::Service>::nil (void)
{
  return ServiceModule::Service::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ServiceModule::Service>::marshal (
    const ServiceModule::Service_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char *
ServiceModule::Service::resolve (
  const char * name)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Service_Proxy_Broker_ == 0)
    {
      ServiceModule_Service_setup_collocation ();
    }
  
  TAO::Arg_Traits< char *>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_name (name);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_name
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "resolve",
      7,
      this->the_TAO_Service_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ServiceModule::Service::_cxx_register (
  const char * name,
  const char * ior)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Service_Proxy_Broker_ == 0)
    {
      ServiceModule_Service_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_name (name);
  TAO::Arg_Traits< char *>::in_arg_val _tao_ior (ior);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_name,
      &_tao_ior
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "register",
      8,
      this->the_TAO_Service_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ServiceModule::Service::notify (
  const char * event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Service_Proxy_Broker_ == 0)
    {
      ServiceModule_Service_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_event (event);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "notify",
      6,
      this->the_TAO_Service_Proxy_Broker_,
      TAO::TAO_ONEWAY_INVOCATION
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Short
ServiceModule::Service::get_status (void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Service_Proxy_Broker_ == 0)
    {
      ServiceModule_Service_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Short>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "get_status",
      10,
      this->the_TAO_Service_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void
ServiceModule::Service::shutdown (void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Service_Proxy_Broker_ == 0)
    {
      ServiceModule_Service_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "shutdown",
      8,
      this->the_TAO_Service_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

ServiceModule::Service::Service (void)
 : the_TAO_Service_Proxy_Broker_ (0)
{
  this->ServiceModule_Service_setup_collocation ();
}

void
ServiceModule::Service::ServiceModule_Service_setup_collocation ()
{
  if (::ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Service_Proxy_Broker_ =
        ::ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer (this);
    }
}

ServiceModule::Service::~Service (void)
{}

void 
ServiceModule::Service::_tao_any_destructor (void *_tao_void_pointer)
{
  Service *_tao_tmp_pointer =
    static_cast<Service *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

ServiceModule::Service_ptr
ServiceModule::Service::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Service>::narrow (
        _tao_objref,
        "IDL:ServiceModule/Service:1.0",
        ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer
      );
}

ServiceModule::Service_ptr
ServiceModule::Service::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Service>::unchecked_narrow (
        _tao_objref,
        "IDL:ServiceModule/Service:1.0",
        ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer
      );
}

ServiceModule::Service_ptr
ServiceModule::Service::_duplicate (Service_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
ServiceModule::Service::_tao_release (Service_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ServiceModule::Service::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:ServiceModule/Service:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* ServiceModule::Service::_interface_repository_id (void) const
{
  return "IDL:ServiceModule/Service:1.0";
}

::CORBA::Boolean
ServiceModule::Service::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_ServiceModule_Service (
    ::CORBA::tk_objref,
    "IDL:ServiceModule/Service:1.0",
    "Service");
  
namespace ServiceModule
{
  ::CORBA::TypeCode_ptr const _tc_Service =
    &_tao_tc_ServiceModule_Service;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<ServiceModule::Service>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ServiceModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Service_ptr _tao_elem)
  {
    Service_ptr _tao_objptr =
      Service::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Service_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Service>::insert (
        _tao_any,
        Service::_tao_any_destructor,
        _tc_Service,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Service_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Service>::extract (
          _tao_any,
          Service::_tao_any_destructor,
          _tc_Service,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ServiceModule::Service_ptr _tao_elem)
{
  ServiceModule::Service_ptr _tao_objptr =
    ServiceModule::Service::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ServiceModule::Service_ptr *_tao_elem)
{
  TAO::Any_Impl_T<ServiceModule::Service>::insert (
      _tao_any,
      ServiceModule::Service::_tao_any_destructor,
      ServiceModule::_tc_Service,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    ServiceModule::Service_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<ServiceModule::Service>::extract (
        _tao_any,
        ServiceModule::Service::_tao_any_destructor,
        ServiceModule::_tc_Service,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const ServiceModule::Service_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    ServiceModule::Service_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::ServiceModule::Service RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        ServiceModule__TAO_Service_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



