// -*- C++ -*-
//
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 *       http://doc.ece.uci.edu/
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:134

#ifndef _TAO_IDL_STREAMC_H_
#define _TAO_IDL_STREAMC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace StreamModule
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:647

#if !defined (_STREAMMODULE_STREAM__VAR_OUT_CH_)
#define _STREAMMODULE_STREAM__VAR_OUT_CH_
  
  class Stream;
  typedef Stream *Stream_ptr;
  
  typedef
    TAO_Objref_Var_T<
        Stream
      >
    Stream_var;
  
  typedef
    TAO_Objref_Out_T<
        Stream
      >
    Stream_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54
  
  class  Stream
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<Stream>;
    typedef Stream_ptr _ptr_type;
    typedef Stream_var _var_type;
    typedef Stream_out _out_type;
    
    // The static operations.
    static Stream_ptr _duplicate (Stream_ptr obj);
    
    static void _tao_release (Stream_ptr obj);
    
    static Stream_ptr _narrow (::CORBA::Object_ptr obj);
    static Stream_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Stream_ptr _nil (void)
    {
      return static_cast<Stream_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Octet
    read_byte (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    write_byte (
      ::CORBA::Octet b);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Boolean
    is_ready (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void
    set_flag (
      ::CORBA::Boolean enabled);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::CORBA::Long
    send_buffer (
      const char * data);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:213
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_Stream_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    Stream (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void StreamModule_Stream_setup_collocation (void);
    
    // Concrete non-local interface only.
    Stream (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Stream (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~Stream (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    Stream (const Stream &);
    
    void operator= (const Stream &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Stream;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module StreamModule

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*StreamModule__TAO_Stream_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_STREAMMODULE_STREAM__TRAITS_)
#define _STREAMMODULE_STREAM__TRAITS_
  
  template<>
  struct  Objref_Traits< ::StreamModule::Stream>
  {
    static ::StreamModule::Stream_ptr duplicate (
        ::StreamModule::Stream_ptr p
      );
    static void release (
        ::StreamModule::Stream_ptr p
      );
    static ::StreamModule::Stream_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::StreamModule::Stream_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace StreamModule
{
   void operator<<= ( ::CORBA::Any &, Stream_ptr); // copying
   void operator<<= ( ::CORBA::Any &, Stream_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Stream_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, StreamModule::Stream_ptr); // copying
 void operator<<= (::CORBA::Any &, StreamModule::Stream_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, StreamModule::Stream_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const StreamModule::Stream_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, StreamModule::Stream_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1452
#if defined (__ACE_INLINE__)
#include "StreamC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


